
CREATE TABLE pokemon_sprites (
    id      VARCHAR(128) PRIMARY KEY,
    name    VARCHAR(256) NOT NULL
);

INSERT INTO pokemon_sprites VALUES ('0001','フシギダネ');
INSERT INTO pokemon_sprites VALUES ('0002','フシギソウ');
INSERT INTO pokemon_sprites VALUES ('0003','フシギバナ');
INSERT INTO pokemon_sprites VALUES ('0003_mega','メガフシギバナ');
INSERT INTO pokemon_sprites VALUES ('0003_gmax','フシギバナ キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0004','ヒトカゲ');
INSERT INTO pokemon_sprites VALUES ('0005','リザード');
INSERT INTO pokemon_sprites VALUES ('0006','リザードン');
INSERT INTO pokemon_sprites VALUES ('0006_mega_x','メガリザードンＸ');
INSERT INTO pokemon_sprites VALUES ('0006_mega_y','メガリザードンＹ');
INSERT INTO pokemon_sprites VALUES ('0006_gmax','リザードン キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0007','ゼニガメ');
INSERT INTO pokemon_sprites VALUES ('0008','カメール');
INSERT INTO pokemon_sprites VALUES ('0009','カメックス');
INSERT INTO pokemon_sprites VALUES ('0009_mega','メガカメックス');
INSERT INTO pokemon_sprites VALUES ('0009_gmax','カメックス キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0010','キャタピー');
INSERT INTO pokemon_sprites VALUES ('0011','トランセル');
INSERT INTO pokemon_sprites VALUES ('0012','バタフリー');
INSERT INTO pokemon_sprites VALUES ('0012_gmax','バタフリー キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0013','ビードル');
INSERT INTO pokemon_sprites VALUES ('0014','コクーン');
INSERT INTO pokemon_sprites VALUES ('0015','スピアー');
INSERT INTO pokemon_sprites VALUES ('0015_mega','メガスピアー');
INSERT INTO pokemon_sprites VALUES ('0016','ポッポ');
INSERT INTO pokemon_sprites VALUES ('0017','ピジョン');
INSERT INTO pokemon_sprites VALUES ('0018','ピジョット');
INSERT INTO pokemon_sprites VALUES ('0018_mega','メガピジョット');
INSERT INTO pokemon_sprites VALUES ('0019','コラッタ');
INSERT INTO pokemon_sprites VALUES ('0019_alola','コラッタ アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0020','ラッタ');
INSERT INTO pokemon_sprites VALUES ('0020_alola','ラッタ アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0021','オニスズメ');
INSERT INTO pokemon_sprites VALUES ('0022','オニドリル');
INSERT INTO pokemon_sprites VALUES ('0023','アーボ');
INSERT INTO pokemon_sprites VALUES ('0024','アーボック');
INSERT INTO pokemon_sprites VALUES ('0025','ピカチュウ');
INSERT INTO pokemon_sprites VALUES ('0025_gmax','ピカチュウ キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0026','ライチュウ');
INSERT INTO pokemon_sprites VALUES ('0026_alola','ライチュウ アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0026_mega_x','メガライチュウＸ');
INSERT INTO pokemon_sprites VALUES ('0026_mega_y','メガライチュウY');
INSERT INTO pokemon_sprites VALUES ('0027','サンド');
INSERT INTO pokemon_sprites VALUES ('0027_alola','サンド アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0028','サンドパン');
INSERT INTO pokemon_sprites VALUES ('0028_alola','サンドパン アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0029','ニドラン♀');
INSERT INTO pokemon_sprites VALUES ('0030','ニドリーナ');
INSERT INTO pokemon_sprites VALUES ('0031','ニドクイン');
INSERT INTO pokemon_sprites VALUES ('0032','ニドラン♂');
INSERT INTO pokemon_sprites VALUES ('0033','ニドリーノ');
INSERT INTO pokemon_sprites VALUES ('0034','ニドキング');
INSERT INTO pokemon_sprites VALUES ('0035','ピッピ');
INSERT INTO pokemon_sprites VALUES ('0036','ピクシー');
INSERT INTO pokemon_sprites VALUES ('0036_mega','メガピクシー');
INSERT INTO pokemon_sprites VALUES ('0037','ロコン');
INSERT INTO pokemon_sprites VALUES ('0037_alola','ロコン アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0038','キュウコン');
INSERT INTO pokemon_sprites VALUES ('0038_alola','キュウコン アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0039','プリン');
INSERT INTO pokemon_sprites VALUES ('0040','プクリン');
INSERT INTO pokemon_sprites VALUES ('0041','ズバット');
INSERT INTO pokemon_sprites VALUES ('0042','ゴルバット');
INSERT INTO pokemon_sprites VALUES ('0043','ナゾノクサ');
INSERT INTO pokemon_sprites VALUES ('0044','クサイハナ');
INSERT INTO pokemon_sprites VALUES ('0045','ラフレシア');
INSERT INTO pokemon_sprites VALUES ('0046','パラス');
INSERT INTO pokemon_sprites VALUES ('0047','パラセクト');
INSERT INTO pokemon_sprites VALUES ('0048','コンパン');
INSERT INTO pokemon_sprites VALUES ('0049','モルフォン');
INSERT INTO pokemon_sprites VALUES ('0050','ディグダ');
INSERT INTO pokemon_sprites VALUES ('0050_alola','ディグダ アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0051','ダグトリオ');
INSERT INTO pokemon_sprites VALUES ('0051_alola','ダグトリオ アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0052','ニャース');
INSERT INTO pokemon_sprites VALUES ('0052_alola','ニャース アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0052_galar','ニャース ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0052_gmax','ニャース キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0053','ペルシアン');
INSERT INTO pokemon_sprites VALUES ('0053_alola','ペルシアン アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0054','コダック');
INSERT INTO pokemon_sprites VALUES ('0055','ゴルダック');
INSERT INTO pokemon_sprites VALUES ('0056','マンキー');
INSERT INTO pokemon_sprites VALUES ('0057','オコリザル');
INSERT INTO pokemon_sprites VALUES ('0058','ガーディ');
INSERT INTO pokemon_sprites VALUES ('0058_hisui','ガーディ ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0059','ウインディ');
INSERT INTO pokemon_sprites VALUES ('0059_hisui','ウインディ ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0060','ニョロモ');
INSERT INTO pokemon_sprites VALUES ('0061','ニョロゾ');
INSERT INTO pokemon_sprites VALUES ('0062','ニョロボン');
INSERT INTO pokemon_sprites VALUES ('0063','ケーシィ');
INSERT INTO pokemon_sprites VALUES ('0064','ユンゲラー');
INSERT INTO pokemon_sprites VALUES ('0065','フーディン');
INSERT INTO pokemon_sprites VALUES ('0065_mega','メガフーディン');
INSERT INTO pokemon_sprites VALUES ('0066','ワンリキー');
INSERT INTO pokemon_sprites VALUES ('0067','ゴーリキー');
INSERT INTO pokemon_sprites VALUES ('0068','カイリキー');
INSERT INTO pokemon_sprites VALUES ('0068_gmax','カイリキー キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0069','マダツボミ');
INSERT INTO pokemon_sprites VALUES ('0070','ウツドン');
INSERT INTO pokemon_sprites VALUES ('0071','ウツボット');
INSERT INTO pokemon_sprites VALUES ('0071_mega','メガウツボット');
INSERT INTO pokemon_sprites VALUES ('0072','メノクラゲ');
INSERT INTO pokemon_sprites VALUES ('0073','ドククラゲ');
INSERT INTO pokemon_sprites VALUES ('0074','イシツブテ');
INSERT INTO pokemon_sprites VALUES ('0074_alola','イシツブテ アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0075','ゴローン');
INSERT INTO pokemon_sprites VALUES ('0075_alola','ゴローン アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0076','ゴローニャ');
INSERT INTO pokemon_sprites VALUES ('0076_alola','ゴローニャ アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0077','ポニータ');
INSERT INTO pokemon_sprites VALUES ('0077_galar','ポニータ ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0078','ギャロップ');
INSERT INTO pokemon_sprites VALUES ('0078_galar','ギャロップ ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0079','ヤドン');
INSERT INTO pokemon_sprites VALUES ('0079_galar','ヤドン ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0080','ヤドラン');
INSERT INTO pokemon_sprites VALUES ('0080_mega','メガヤドラン');
INSERT INTO pokemon_sprites VALUES ('0080_galar','ヤドラン ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0081','コイル');
INSERT INTO pokemon_sprites VALUES ('0082','レアコイル');
INSERT INTO pokemon_sprites VALUES ('0083','カモネギ');
INSERT INTO pokemon_sprites VALUES ('0083_galar','カモネギ ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0084','ドードー');
INSERT INTO pokemon_sprites VALUES ('0085','ドードリオ');
INSERT INTO pokemon_sprites VALUES ('0086','パウワウ');
INSERT INTO pokemon_sprites VALUES ('0087','ジュゴン');
INSERT INTO pokemon_sprites VALUES ('0088','ベトベター');
INSERT INTO pokemon_sprites VALUES ('0088_alola','ベトベター アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0089','ベトベトン');
INSERT INTO pokemon_sprites VALUES ('0089_alola','ベトベトン アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0090','シェルダー');
INSERT INTO pokemon_sprites VALUES ('0091','パルシェン');
INSERT INTO pokemon_sprites VALUES ('0092','ゴース');
INSERT INTO pokemon_sprites VALUES ('0093','ゴースト');
INSERT INTO pokemon_sprites VALUES ('0094','ゲンガー');
INSERT INTO pokemon_sprites VALUES ('0094_mega','メガゲンガー');
INSERT INTO pokemon_sprites VALUES ('0094_gmax','ゲンガー キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0095','イワーク');
INSERT INTO pokemon_sprites VALUES ('0096','スリープ');
INSERT INTO pokemon_sprites VALUES ('0097','スリーパー');
INSERT INTO pokemon_sprites VALUES ('0098','クラブ');
INSERT INTO pokemon_sprites VALUES ('0099','キングラー');
INSERT INTO pokemon_sprites VALUES ('0099_gmax','キングラー キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0100','ビリリダマ');
INSERT INTO pokemon_sprites VALUES ('0100_hisui','ビリリダマ ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0101','マルマイン');
INSERT INTO pokemon_sprites VALUES ('0101_hisui','マルマイン ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0102', 'タマタマ');
INSERT INTO pokemon_sprites VALUES ('0103', 'ナッシー');
INSERT INTO pokemon_sprites VALUES ('0103_alola', 'ナッシー アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0104', 'カラカラ');
INSERT INTO pokemon_sprites VALUES ('0105', 'ガラガラ');
INSERT INTO pokemon_sprites VALUES ('0105_alola', 'ガラガラ アローラのすがた');
INSERT INTO pokemon_sprites VALUES ('0106', 'サワムラー');
INSERT INTO pokemon_sprites VALUES ('0107', 'エビワラー');
INSERT INTO pokemon_sprites VALUES ('0108', 'ベロリンガ');
INSERT INTO pokemon_sprites VALUES ('0109', 'ドガース');
INSERT INTO pokemon_sprites VALUES ('0110', 'マタドガス');
INSERT INTO pokemon_sprites VALUES ('0110_galar', 'マタドガス ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0111', 'サイホーン');
INSERT INTO pokemon_sprites VALUES ('0112', 'サイドン');
INSERT INTO pokemon_sprites VALUES ('0113', 'ラッキー');
INSERT INTO pokemon_sprites VALUES ('0114', 'モンジャラ');
INSERT INTO pokemon_sprites VALUES ('0115', 'ガルーラ');
INSERT INTO pokemon_sprites VALUES ('0115_mega', 'メガガルーラ');
INSERT INTO pokemon_sprites VALUES ('0116', 'タッツー');
INSERT INTO pokemon_sprites VALUES ('0117', 'シードラ');
INSERT INTO pokemon_sprites VALUES ('0118', 'トサキント');
INSERT INTO pokemon_sprites VALUES ('0119', 'アズマオウ');
INSERT INTO pokemon_sprites VALUES ('0120', 'ヒトデマン');
INSERT INTO pokemon_sprites VALUES ('0121', 'スターミー');
INSERT INTO pokemon_sprites VALUES ('0121_mega', 'メガスターミー');
INSERT INTO pokemon_sprites VALUES ('0122', 'バリヤード');
INSERT INTO pokemon_sprites VALUES ('0122_galar', 'バリヤード ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0123', 'ストライク');
INSERT INTO pokemon_sprites VALUES ('0124', 'ルージュラ');
INSERT INTO pokemon_sprites VALUES ('0125', 'エレブー');
INSERT INTO pokemon_sprites VALUES ('0126', 'ブーバー');
INSERT INTO pokemon_sprites VALUES ('0127', 'カイロス');
INSERT INTO pokemon_sprites VALUES ('0127_mega', 'メガカイロス');
INSERT INTO pokemon_sprites VALUES ('0128', 'ケンタロス');
INSERT INTO pokemon_sprites VALUES ('0128_paldea_combat', 'ケンタロス パルデアのすがた・コンバット種');
INSERT INTO pokemon_sprites VALUES ('0128_paldea_blaze', 'ケンタロス パルデアのすがた・ブレイズ種');
INSERT INTO pokemon_sprites VALUES ('0128_paldea_aqua', 'ケンタロス パルデアのすがた・ウォーター種');
INSERT INTO pokemon_sprites VALUES ('0129', 'コイキング');
INSERT INTO pokemon_sprites VALUES ('0130', 'ギャラドス');
INSERT INTO pokemon_sprites VALUES ('0130_mega', 'メガギャラドス');
INSERT INTO pokemon_sprites VALUES ('0131', 'ラプラス');
INSERT INTO pokemon_sprites VALUES ('0131_gmax', 'ラプラス キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0132', 'メタモン');
INSERT INTO pokemon_sprites VALUES ('0133', 'イーブイ');
INSERT INTO pokemon_sprites VALUES ('0133_gmax', 'イーブイ キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0134', 'シャワーズ');
INSERT INTO pokemon_sprites VALUES ('0135', 'サンダース');
INSERT INTO pokemon_sprites VALUES ('0136', 'ブースター');
INSERT INTO pokemon_sprites VALUES ('0137', 'ポリゴン');
INSERT INTO pokemon_sprites VALUES ('0138', 'オムナイト');
INSERT INTO pokemon_sprites VALUES ('0139', 'オムスター');
INSERT INTO pokemon_sprites VALUES ('0140', 'カブト');
INSERT INTO pokemon_sprites VALUES ('0141', 'カブトプス');
INSERT INTO pokemon_sprites VALUES ('0142', 'プテラ');
INSERT INTO pokemon_sprites VALUES ('0142_mega', 'メガプテラ');
INSERT INTO pokemon_sprites VALUES ('0143', 'カビゴン');
INSERT INTO pokemon_sprites VALUES ('0143_gmax', 'カビゴン キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0144', 'フリーザー');
INSERT INTO pokemon_sprites VALUES ('0144_galar', 'フリーザー ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0145', 'サンダー');
INSERT INTO pokemon_sprites VALUES ('0145_galar', 'サンダー ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0146', 'ファイヤー');
INSERT INTO pokemon_sprites VALUES ('0146_galar', 'ファイヤー ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0147', 'ミニリュウ');
INSERT INTO pokemon_sprites VALUES ('0148', 'ハクリュー');
INSERT INTO pokemon_sprites VALUES ('0149', 'カイリュー');
INSERT INTO pokemon_sprites VALUES ('0150', 'ミュウツー');
INSERT INTO pokemon_sprites VALUES ('0150_mega_x', 'メガミュウツーX');
INSERT INTO pokemon_sprites VALUES ('0150_mega_y', 'メガミュウツーY');
INSERT INTO pokemon_sprites VALUES ('0151', 'ミュウ');

INSERT INTO pokemon_sprites VALUES ('0152','チコリータ');
INSERT INTO pokemon_sprites VALUES ('0153','ベイリーフ');
INSERT INTO pokemon_sprites VALUES ('0154','メガニウム');
INSERT INTO pokemon_sprites VALUES ('0154_mega','メガメガニウム');
INSERT INTO pokemon_sprites VALUES ('0155','ヒノアラシ');
INSERT INTO pokemon_sprites VALUES ('0156','マグマラシ');
INSERT INTO pokemon_sprites VALUES ('0157','バクフーン');
INSERT INTO pokemon_sprites VALUES ('0157_hisui','バクフーン ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0158','ワニノコ');
INSERT INTO pokemon_sprites VALUES ('0159','アリゲイツ');
INSERT INTO pokemon_sprites VALUES ('0160','オーダイル');
INSERT INTO pokemon_sprites VALUES ('0160_mega','メガオーダイル');
INSERT INTO pokemon_sprites VALUES ('0161','オタチ');
INSERT INTO pokemon_sprites VALUES ('0162','オオタチ');
INSERT INTO pokemon_sprites VALUES ('0163','ホーホー');
INSERT INTO pokemon_sprites VALUES ('0164','ヨルノズク');
INSERT INTO pokemon_sprites VALUES ('0165','レディバ');
INSERT INTO pokemon_sprites VALUES ('0166','レディアン');
INSERT INTO pokemon_sprites VALUES ('0167','イトマル');
INSERT INTO pokemon_sprites VALUES ('0168','アリアドス');
INSERT INTO pokemon_sprites VALUES ('0169','クロバット');
INSERT INTO pokemon_sprites VALUES ('0170','チョンチー');
INSERT INTO pokemon_sprites VALUES ('0171','ランターン');
INSERT INTO pokemon_sprites VALUES ('0172','ピチュー');
INSERT INTO pokemon_sprites VALUES ('0173','ピィ');
INSERT INTO pokemon_sprites VALUES ('0174','ププリン');
INSERT INTO pokemon_sprites VALUES ('0175','トゲピー');
INSERT INTO pokemon_sprites VALUES ('0176','トゲチック');
INSERT INTO pokemon_sprites VALUES ('0177','ネイティ');
INSERT INTO pokemon_sprites VALUES ('0178','ネイティオ');
INSERT INTO pokemon_sprites VALUES ('0179','メリープ');
INSERT INTO pokemon_sprites VALUES ('0180','モココ');
INSERT INTO pokemon_sprites VALUES ('0181','デンリュウ');
INSERT INTO pokemon_sprites VALUES ('0181_mega','メガデンリュウ');
INSERT INTO pokemon_sprites VALUES ('0182','キレイハナ');
INSERT INTO pokemon_sprites VALUES ('0183','マリル');
INSERT INTO pokemon_sprites VALUES ('0184','マリルリ');
INSERT INTO pokemon_sprites VALUES ('0185','ウソッキー');
INSERT INTO pokemon_sprites VALUES ('0186','ニョロトノ');
INSERT INTO pokemon_sprites VALUES ('0187','ハネッコ');
INSERT INTO pokemon_sprites VALUES ('0188','ポポッコ');
INSERT INTO pokemon_sprites VALUES ('0189','ワタッコ');
INSERT INTO pokemon_sprites VALUES ('0190','エイパム');
INSERT INTO pokemon_sprites VALUES ('0191','ヒマナッツ');
INSERT INTO pokemon_sprites VALUES ('0192','キマワリ');
INSERT INTO pokemon_sprites VALUES ('0193','ヤンヤンマ');
INSERT INTO pokemon_sprites VALUES ('0194','ウパー');
INSERT INTO pokemon_sprites VALUES ('0194_paldea','ウパー パルデアのすがた');
INSERT INTO pokemon_sprites VALUES ('0195','ヌオー');
INSERT INTO pokemon_sprites VALUES ('0196','エーフィ');
INSERT INTO pokemon_sprites VALUES ('0197','ブラッキー');
INSERT INTO pokemon_sprites VALUES ('0198','ヤミカラス');
INSERT INTO pokemon_sprites VALUES ('0199','ヤドキング');
INSERT INTO pokemon_sprites VALUES ('0199_galar','ヤドキング ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0200','ムウマ');
INSERT INTO pokemon_sprites VALUES ('0201','アンノーン');
INSERT INTO pokemon_sprites VALUES ('0201_A','アンノーン Aのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_B','アンノーン Bのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_C','アンノーン Cのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_D','アンノーン Dのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_E','アンノーン Eのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_F','アンノーン Fのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_G','アンノーン Gのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_H','アンノーン Hのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_I','アンノーン Iのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_J','アンノーン Jのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_K','アンノーン Kのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_L','アンノーン Lのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_M','アンノーン Mのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_N','アンノーン Nのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_O','アンノーン Oのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_P','アンノーン Pのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_Q','アンノーン Qのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_R','アンノーン Rのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_S','アンノーン Sのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_T','アンノーン Tのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_U','アンノーン Uのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_V','アンノーン Vのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_W','アンノーン Wのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_X','アンノーン Xのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_Y','アンノーン Yのかたち');
INSERT INTO pokemon_sprites VALUES ('0201_Z','アンノーン Zのかたち');
INSERT INTO pokemon_sprites VALUES ('0202','ソーナンス');
INSERT INTO pokemon_sprites VALUES ('0203','キリンリキ');
INSERT INTO pokemon_sprites VALUES ('0204','クヌギダマ');
INSERT INTO pokemon_sprites VALUES ('0205','フォレトス');
INSERT INTO pokemon_sprites VALUES ('0206','ノコッチ');
INSERT INTO pokemon_sprites VALUES ('0207','グライガー');
INSERT INTO pokemon_sprites VALUES ('0208','ハガネール');
INSERT INTO pokemon_sprites VALUES ('0208_mega','メガハガネール');
INSERT INTO pokemon_sprites VALUES ('0209','ブルー');
INSERT INTO pokemon_sprites VALUES ('0210','グランブル');
INSERT INTO pokemon_sprites VALUES ('0211','ハリーセン');
INSERT INTO pokemon_sprites VALUES ('0211_hisui','ハリーセン ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0212','ハッサム');
INSERT INTO pokemon_sprites VALUES ('0212_mega','メガハッサム');
INSERT INTO pokemon_sprites VALUES ('0213','ツボツボ');
INSERT INTO pokemon_sprites VALUES ('0214','ヘラクロス');
INSERT INTO pokemon_sprites VALUES ('0214_mega','メガヘラクロス');
INSERT INTO pokemon_sprites VALUES ('0215','ニューラ');
INSERT INTO pokemon_sprites VALUES ('0215_hisui','ニューラ ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0216','ヒメグマ');
INSERT INTO pokemon_sprites VALUES ('0217','リングマ');
INSERT INTO pokemon_sprites VALUES ('0218','マグマッグ');
INSERT INTO pokemon_sprites VALUES ('0219','マグカルゴ');
INSERT INTO pokemon_sprites VALUES ('0220','ウリムー');
INSERT INTO pokemon_sprites VALUES ('0221','イノムー');
INSERT INTO pokemon_sprites VALUES ('0222','サニーゴ');
INSERT INTO pokemon_sprites VALUES ('0222_galar','サニーゴ ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0223','テッポウオ');
INSERT INTO pokemon_sprites VALUES ('0224','オクタン');
INSERT INTO pokemon_sprites VALUES ('0225','デリバード');
INSERT INTO pokemon_sprites VALUES ('0226','マンタイン');
INSERT INTO pokemon_sprites VALUES ('0227','エアームド');
INSERT INTO pokemon_sprites VALUES ('0227_mega','メガエアームド');
INSERT INTO pokemon_sprites VALUES ('0228','デルビル');
INSERT INTO pokemon_sprites VALUES ('0229','ヘルガー');
INSERT INTO pokemon_sprites VALUES ('0229_mega','メガヘルガー');
INSERT INTO pokemon_sprites VALUES ('0230','キングドラ');
INSERT INTO pokemon_sprites VALUES ('0231','ゴマゾウ');
INSERT INTO pokemon_sprites VALUES ('0232','ドンファン');
INSERT INTO pokemon_sprites VALUES ('0233','ポリゴン２');
INSERT INTO pokemon_sprites VALUES ('0234','オドシシ');
INSERT INTO pokemon_sprites VALUES ('0235','ドーブル');
INSERT INTO pokemon_sprites VALUES ('0236','バルキー');
INSERT INTO pokemon_sprites VALUES ('0237','カポエラー');
INSERT INTO pokemon_sprites VALUES ('0238','ムチュール');
INSERT INTO pokemon_sprites VALUES ('0239','エレキッド');
INSERT INTO pokemon_sprites VALUES ('0240','ブビィ');
INSERT INTO pokemon_sprites VALUES ('0241','ミルタンク');
INSERT INTO pokemon_sprites VALUES ('0242','ハピナス');
INSERT INTO pokemon_sprites VALUES ('0243','ライコウ');
INSERT INTO pokemon_sprites VALUES ('0244','エンテイ');
INSERT INTO pokemon_sprites VALUES ('0245','スイクン');
INSERT INTO pokemon_sprites VALUES ('0246','ヨーギラス');
INSERT INTO pokemon_sprites VALUES ('0247','サナギラス');
INSERT INTO pokemon_sprites VALUES ('0248','バンギラス');
INSERT INTO pokemon_sprites VALUES ('0248_mega','メガバンギラス');
INSERT INTO pokemon_sprites VALUES ('0249','ルギア');
INSERT INTO pokemon_sprites VALUES ('0250','ホウオウ');
INSERT INTO pokemon_sprites VALUES ('0251','セレビィ');

INSERT INTO pokemon_sprites VALUES ('0252','キモリ');
INSERT INTO pokemon_sprites VALUES ('0253','ジュプトル');
INSERT INTO pokemon_sprites VALUES ('0254','ジュカイン');
INSERT INTO pokemon_sprites VALUES ('0254_mega','メガジュカイン');
INSERT INTO pokemon_sprites VALUES ('0255','アチャモ');
INSERT INTO pokemon_sprites VALUES ('0256','ワカシャモ');
INSERT INTO pokemon_sprites VALUES ('0257','バシャーモ');
INSERT INTO pokemon_sprites VALUES ('0257_mega','メガバシャーモ');
INSERT INTO pokemon_sprites VALUES ('0258','ミズゴロウ');
INSERT INTO pokemon_sprites VALUES ('0259','ヌマクロー');
INSERT INTO pokemon_sprites VALUES ('0260','ラグラージ');
INSERT INTO pokemon_sprites VALUES ('0260_mega','メガラグラージ');
INSERT INTO pokemon_sprites VALUES ('0261','ポチエナ');
INSERT INTO pokemon_sprites VALUES ('0262','グラエナ');
INSERT INTO pokemon_sprites VALUES ('0263','ジグザグマ');
INSERT INTO pokemon_sprites VALUES ('0264','マッスグマ');
INSERT INTO pokemon_sprites VALUES ('0265','ケムッソ');
INSERT INTO pokemon_sprites VALUES ('0266','カラサリス');
INSERT INTO pokemon_sprites VALUES ('0267','アゲハント');
INSERT INTO pokemon_sprites VALUES ('0268','マユルド');
INSERT INTO pokemon_sprites VALUES ('0269','ドクケイル');
INSERT INTO pokemon_sprites VALUES ('0270','ハスボー');
INSERT INTO pokemon_sprites VALUES ('0271','ハスブレロ');
INSERT INTO pokemon_sprites VALUES ('0272','ルンパッパ');
INSERT INTO pokemon_sprites VALUES ('0273','タネボー');
INSERT INTO pokemon_sprites VALUES ('0274','コノハナ');
INSERT INTO pokemon_sprites VALUES ('0275','ダーテング');
INSERT INTO pokemon_sprites VALUES ('0276','スバメ');
INSERT INTO pokemon_sprites VALUES ('0277','オオスバメ');
INSERT INTO pokemon_sprites VALUES ('0278','キャモメ');
INSERT INTO pokemon_sprites VALUES ('0279','ペリッパー');
INSERT INTO pokemon_sprites VALUES ('0280','ラルトス');
INSERT INTO pokemon_sprites VALUES ('0281','キルリア');
INSERT INTO pokemon_sprites VALUES ('0282','サーナイト');
INSERT INTO pokemon_sprites VALUES ('0282_mega','メガサーナイト');
INSERT INTO pokemon_sprites VALUES ('0283','アメタマ');
INSERT INTO pokemon_sprites VALUES ('0284','アメモース');
INSERT INTO pokemon_sprites VALUES ('0285','キノココ');
INSERT INTO pokemon_sprites VALUES ('0286','キノガッサ');
INSERT INTO pokemon_sprites VALUES ('0287','ナマケロ');
INSERT INTO pokemon_sprites VALUES ('0288','ヤルキモノ');
INSERT INTO pokemon_sprites VALUES ('0289','ケッキング');
INSERT INTO pokemon_sprites VALUES ('0290','ツチニン');
INSERT INTO pokemon_sprites VALUES ('0291','テッカニン');
INSERT INTO pokemon_sprites VALUES ('0292','ヌケニン');
INSERT INTO pokemon_sprites VALUES ('0293','ゴニョニョ');
INSERT INTO pokemon_sprites VALUES ('0294','ドゴーム');
INSERT INTO pokemon_sprites VALUES ('0295','バクオング');
INSERT INTO pokemon_sprites VALUES ('0296','マクノシタ');
INSERT INTO pokemon_sprites VALUES ('0297','ハリテヤマ');
INSERT INTO pokemon_sprites VALUES ('0298','ルリリ');
INSERT INTO pokemon_sprites VALUES ('0299','ノズパス');
INSERT INTO pokemon_sprites VALUES ('0300','エネコ');
INSERT INTO pokemon_sprites VALUES ('0301','エネコロロ');
INSERT INTO pokemon_sprites VALUES ('0302','ヤミラミ');
INSERT INTO pokemon_sprites VALUES ('0302_mega','メガヤミラミ');
INSERT INTO pokemon_sprites VALUES ('0303','クチート');
INSERT INTO pokemon_sprites VALUES ('0303_mega','メガクチート');
INSERT INTO pokemon_sprites VALUES ('0304','ココドラ');
INSERT INTO pokemon_sprites VALUES ('0305','コドラ');
INSERT INTO pokemon_sprites VALUES ('0306','ボスゴドラ');
INSERT INTO pokemon_sprites VALUES ('0306_mega','メガボスゴドラ');
INSERT INTO pokemon_sprites VALUES ('0307','アサナン');
INSERT INTO pokemon_sprites VALUES ('0308','チャーレム');
INSERT INTO pokemon_sprites VALUES ('0308_mega','メガチャーレム');
INSERT INTO pokemon_sprites VALUES ('0309','ラクライ');
INSERT INTO pokemon_sprites VALUES ('0310','ライボルト');
INSERT INTO pokemon_sprites VALUES ('0310_mega','メガライボルト');
INSERT INTO pokemon_sprites VALUES ('0311','プラスル');
INSERT INTO pokemon_sprites VALUES ('0312','マイナン');
INSERT INTO pokemon_sprites VALUES ('0313','バルビート');
INSERT INTO pokemon_sprites VALUES ('0314','イルミーゼ');
INSERT INTO pokemon_sprites VALUES ('0315','ロゼリア');
INSERT INTO pokemon_sprites VALUES ('0316','ゴクリン');
INSERT INTO pokemon_sprites VALUES ('0317','マルノーム');
INSERT INTO pokemon_sprites VALUES ('0318','キバニア');
INSERT INTO pokemon_sprites VALUES ('0319','サメハダー');
INSERT INTO pokemon_sprites VALUES ('0319_mega','メガサメハダー');
INSERT INTO pokemon_sprites VALUES ('0320','ホエルコ');
INSERT INTO pokemon_sprites VALUES ('0321','ホエルオー');
INSERT INTO pokemon_sprites VALUES ('0322','ドンメル');
INSERT INTO pokemon_sprites VALUES ('0323','バクーダ');
INSERT INTO pokemon_sprites VALUES ('0323_mega','メガバクーダ');
INSERT INTO pokemon_sprites VALUES ('0324','コータス');
INSERT INTO pokemon_sprites VALUES ('0325','バネブー');
INSERT INTO pokemon_sprites VALUES ('0326','ブーピッグ');
INSERT INTO pokemon_sprites VALUES ('0327','パッチール');
INSERT INTO pokemon_sprites VALUES ('0328','ナックラー');
INSERT INTO pokemon_sprites VALUES ('0329','ビブラーバ');
INSERT INTO pokemon_sprites VALUES ('0330','フライゴン');
INSERT INTO pokemon_sprites VALUES ('0331','サボネア');
INSERT INTO pokemon_sprites VALUES ('0332','ノクタス');
INSERT INTO pokemon_sprites VALUES ('0333','チルット');
INSERT INTO pokemon_sprites VALUES ('0334','チルタリス');
INSERT INTO pokemon_sprites VALUES ('0334_mega','メガチルタリス');
INSERT INTO pokemon_sprites VALUES ('0335','ザングース');
INSERT INTO pokemon_sprites VALUES ('0336','ハブネーク');
INSERT INTO pokemon_sprites VALUES ('0337','ルナトーン');
INSERT INTO pokemon_sprites VALUES ('0338','ソルロック');
INSERT INTO pokemon_sprites VALUES ('0339','ドジョッチ');
INSERT INTO pokemon_sprites VALUES ('0340','ナマズン');
INSERT INTO pokemon_sprites VALUES ('0341','ヘイガニ');
INSERT INTO pokemon_sprites VALUES ('0342','シザリガー');
INSERT INTO pokemon_sprites VALUES ('0343','ヤジロン');
INSERT INTO pokemon_sprites VALUES ('0344','ネンドール');
INSERT INTO pokemon_sprites VALUES ('0345','リリーラ');
INSERT INTO pokemon_sprites VALUES ('0346','ユレイドル');
INSERT INTO pokemon_sprites VALUES ('0347','アノプス');
INSERT INTO pokemon_sprites VALUES ('0348','アーマルド');
INSERT INTO pokemon_sprites VALUES ('0349','ヒンバス');
INSERT INTO pokemon_sprites VALUES ('0350','ミロカロス');
INSERT INTO pokemon_sprites VALUES ('0351','ポワルン');
INSERT INTO pokemon_sprites VALUES ('0351_sunny','ポワルン たいようのすがた');
INSERT INTO pokemon_sprites VALUES ('0351_rainy','ポワルン あまみずのすがた');
INSERT INTO pokemon_sprites VALUES ('0351_snowy','ポワルン ゆきぐものすがた');
INSERT INTO pokemon_sprites VALUES ('0352','カクレオン');
INSERT INTO pokemon_sprites VALUES ('0353','カゲボウズ');
INSERT INTO pokemon_sprites VALUES ('0354','ジュペッタ');
INSERT INTO pokemon_sprites VALUES ('0354_mega','メガジュペッタ');
INSERT INTO pokemon_sprites VALUES ('0355','ヨマワル');
INSERT INTO pokemon_sprites VALUES ('0356','サマヨール');
INSERT INTO pokemon_sprites VALUES ('0357','トロピウス');
INSERT INTO pokemon_sprites VALUES ('0358','チリーン');
INSERT INTO pokemon_sprites VALUES ('0359','アブソル');
INSERT INTO pokemon_sprites VALUES ('0359_mega','メガアブソル');
INSERT INTO pokemon_sprites VALUES ('0359_mega_z','メガアブソルZ');
INSERT INTO pokemon_sprites VALUES ('0360','ソーナノ');
INSERT INTO pokemon_sprites VALUES ('0361','ユキワラシ');
INSERT INTO pokemon_sprites VALUES ('0362','オニゴーリ');
INSERT INTO pokemon_sprites VALUES ('0362_mega','メガオニゴーリ');
INSERT INTO pokemon_sprites VALUES ('0363','タマザラシ');
INSERT INTO pokemon_sprites VALUES ('0364','トドグラー');
INSERT INTO pokemon_sprites VALUES ('0365','トドゼルガ');
INSERT INTO pokemon_sprites VALUES ('0366','パールル');
INSERT INTO pokemon_sprites VALUES ('0367','ハンテール');
INSERT INTO pokemon_sprites VALUES ('0368','サクラビス');
INSERT INTO pokemon_sprites VALUES ('0369','ジーランス');
INSERT INTO pokemon_sprites VALUES ('0370','ラブカス');
INSERT INTO pokemon_sprites VALUES ('0371','タツベイ');
INSERT INTO pokemon_sprites VALUES ('0372','コモルー');
INSERT INTO pokemon_sprites VALUES ('0373','ボーマンダ');
INSERT INTO pokemon_sprites VALUES ('0373_mega','メガボーマンダ');
INSERT INTO pokemon_sprites VALUES ('0374','ダンバル');
INSERT INTO pokemon_sprites VALUES ('0375','メタング');
INSERT INTO pokemon_sprites VALUES ('0376','メタグロス');
INSERT INTO pokemon_sprites VALUES ('0376_mega','メガメタグロス');
INSERT INTO pokemon_sprites VALUES ('0377','レジロック');
INSERT INTO pokemon_sprites VALUES ('0378','レジアイス');
INSERT INTO pokemon_sprites VALUES ('0379','レジスチル');
INSERT INTO pokemon_sprites VALUES ('0380','ラティアス');
INSERT INTO pokemon_sprites VALUES ('0380_mega','メガラティアス');
INSERT INTO pokemon_sprites VALUES ('0381','ラティオス');
INSERT INTO pokemon_sprites VALUES ('0381_mega','メガラティオス');
INSERT INTO pokemon_sprites VALUES ('0382','カイオーガ');
INSERT INTO pokemon_sprites VALUES ('0382_primal','ゲンシカイオーガ');
INSERT INTO pokemon_sprites VALUES ('0383','グラードン');
INSERT INTO pokemon_sprites VALUES ('0383_primal','ゲンシグラードン');
INSERT INTO pokemon_sprites VALUES ('0384','レックウザ');
INSERT INTO pokemon_sprites VALUES ('0384_mega','メガレックウザ');
INSERT INTO pokemon_sprites VALUES ('0385','ジラーチ');
INSERT INTO pokemon_sprites VALUES ('0386','デオキシス');
INSERT INTO pokemon_sprites VALUES ('0386_normal','デオキシス ノーマルフォルム');
INSERT INTO pokemon_sprites VALUES ('0386_attack','デオキシス アタックフォルム');
INSERT INTO pokemon_sprites VALUES ('0386_defense','デオキシス ディフェンスフォルム');
INSERT INTO pokemon_sprites VALUES ('0386_speed','デオキシス スピードフォルム');

INSERT INTO pokemon_sprites VALUES ('0387','ナエトル');
INSERT INTO pokemon_sprites VALUES ('0388','ハヤシガメ');
INSERT INTO pokemon_sprites VALUES ('0389','ドダイトス');
INSERT INTO pokemon_sprites VALUES ('0390','ヒコザル');
INSERT INTO pokemon_sprites VALUES ('0391','モウカザル');
INSERT INTO pokemon_sprites VALUES ('0392','ゴウカザル');
INSERT INTO pokemon_sprites VALUES ('0393','ポッチャマ');
INSERT INTO pokemon_sprites VALUES ('0394','ポッタイシ');
INSERT INTO pokemon_sprites VALUES ('0395','エンペルト');
INSERT INTO pokemon_sprites VALUES ('0396','ムックル');
INSERT INTO pokemon_sprites VALUES ('0397','ムクバード');
INSERT INTO pokemon_sprites VALUES ('0398','ムクホーク');
INSERT INTO pokemon_sprites VALUES ('0398_mega','メガムクホーク');
INSERT INTO pokemon_sprites VALUES ('0399','ビッパ');
INSERT INTO pokemon_sprites VALUES ('0400','ビーダル');
INSERT INTO pokemon_sprites VALUES ('0401','コロボーシ');
INSERT INTO pokemon_sprites VALUES ('0402','コロトック');
INSERT INTO pokemon_sprites VALUES ('0403','コリンク');
INSERT INTO pokemon_sprites VALUES ('0404','ルクシオ');
INSERT INTO pokemon_sprites VALUES ('0405','レントラー');
INSERT INTO pokemon_sprites VALUES ('0406','スボミー');
INSERT INTO pokemon_sprites VALUES ('0407','ロズレイド');
INSERT INTO pokemon_sprites VALUES ('0408','ズガイドス');
INSERT INTO pokemon_sprites VALUES ('0409','ラムパルド');
INSERT INTO pokemon_sprites VALUES ('0410','タテトプス');
INSERT INTO pokemon_sprites VALUES ('0411','トリデプス');
INSERT INTO pokemon_sprites VALUES ('0412','ミノムッチ');
INSERT INTO pokemon_sprites VALUES ('0412_plant','ミノムッチ くさきのミノ');
INSERT INTO pokemon_sprites VALUES ('0412_sandy','ミノムッチ すなちのミノ');
INSERT INTO pokemon_sprites VALUES ('0412_trash','ミノムッチ ゴミのミノ');
INSERT INTO pokemon_sprites VALUES ('0413','ミノマダム');
INSERT INTO pokemon_sprites VALUES ('0413_plant','ミノマダム くさきのミノ');
INSERT INTO pokemon_sprites VALUES ('0413_sandy','ミノマダム すなちのミノ');
INSERT INTO pokemon_sprites VALUES ('0413_trash','ミノマダム ゴミのミノ');
INSERT INTO pokemon_sprites VALUES ('0414','ガーメイル');
INSERT INTO pokemon_sprites VALUES ('0415','ミツハニー');
INSERT INTO pokemon_sprites VALUES ('0416','ビークイン');
INSERT INTO pokemon_sprites VALUES ('0417','パチリス');
INSERT INTO pokemon_sprites VALUES ('0418','ブイゼル');
INSERT INTO pokemon_sprites VALUES ('0419','フローゼル');
INSERT INTO pokemon_sprites VALUES ('0420','チェリンボ');
INSERT INTO pokemon_sprites VALUES ('0421','チェリム');
INSERT INTO pokemon_sprites VALUES ('0421_overcast','チェリム ネガフォルム');
INSERT INTO pokemon_sprites VALUES ('0421_sunshine','チェリム ポジフォルム');
INSERT INTO pokemon_sprites VALUES ('0422','カラナクシ');
INSERT INTO pokemon_sprites VALUES ('0422_west','カラナクシ にしのうみ');
INSERT INTO pokemon_sprites VALUES ('0422_east','カラナクシ ひがしのうみ');
INSERT INTO pokemon_sprites VALUES ('0423','トリトドン');
INSERT INTO pokemon_sprites VALUES ('0423_west','トリトドン にしのうみ');
INSERT INTO pokemon_sprites VALUES ('0423_east','トリトドン ひがしのうみ');
INSERT INTO pokemon_sprites VALUES ('0424','エテボース');
INSERT INTO pokemon_sprites VALUES ('0425','フワンテ');
INSERT INTO pokemon_sprites VALUES ('0426','フワライド');
INSERT INTO pokemon_sprites VALUES ('0427','ミミロル');
INSERT INTO pokemon_sprites VALUES ('0428','ミミロップ');
INSERT INTO pokemon_sprites VALUES ('0428_mega','メガミミロップ');
INSERT INTO pokemon_sprites VALUES ('0429','ムウマージ');
INSERT INTO pokemon_sprites VALUES ('0430','ドンカラス');
INSERT INTO pokemon_sprites VALUES ('0431','ニャルマー');
INSERT INTO pokemon_sprites VALUES ('0432','ブニャット');
INSERT INTO pokemon_sprites VALUES ('0433','リーシャン');
INSERT INTO pokemon_sprites VALUES ('0434','スカンプー');
INSERT INTO pokemon_sprites VALUES ('0435','スカタンク');
INSERT INTO pokemon_sprites VALUES ('0436','ドーミラー');
INSERT INTO pokemon_sprites VALUES ('0437','ドータクン');
INSERT INTO pokemon_sprites VALUES ('0438','ウソハチ');
INSERT INTO pokemon_sprites VALUES ('0439','マネネ');
INSERT INTO pokemon_sprites VALUES ('0440','ピンプク');
INSERT INTO pokemon_sprites VALUES ('0441','ペラップ');
INSERT INTO pokemon_sprites VALUES ('0442','ミカルゲ');
INSERT INTO pokemon_sprites VALUES ('0443','フカマル');
INSERT INTO pokemon_sprites VALUES ('0444','ガバイト');
INSERT INTO pokemon_sprites VALUES ('0445','ガブリアス');
INSERT INTO pokemon_sprites VALUES ('0445_mega','メガガブリアス');
INSERT INTO pokemon_sprites VALUES ('0445_mega_z','メガガブリアスZ');
INSERT INTO pokemon_sprites VALUES ('0446','ゴンベ');
INSERT INTO pokemon_sprites VALUES ('0447','リオル');
INSERT INTO pokemon_sprites VALUES ('0448','ルカリオ');
INSERT INTO pokemon_sprites VALUES ('0448_mega','メガルカリオ');
INSERT INTO pokemon_sprites VALUES ('0448_mega_z','メガルカリオZ');
INSERT INTO pokemon_sprites VALUES ('0449','ヒポポタス');
INSERT INTO pokemon_sprites VALUES ('0450','カバルドン');
INSERT INTO pokemon_sprites VALUES ('0451','スコルピ');
INSERT INTO pokemon_sprites VALUES ('0452','ドラピオン');
INSERT INTO pokemon_sprites VALUES ('0453','グレッグル');
INSERT INTO pokemon_sprites VALUES ('0454','ドクロッグ');
INSERT INTO pokemon_sprites VALUES ('0455','マスキッパ');
INSERT INTO pokemon_sprites VALUES ('0456','ケイコウオ');
INSERT INTO pokemon_sprites VALUES ('0457','ネオラント');
INSERT INTO pokemon_sprites VALUES ('0458','タマンタ');
INSERT INTO pokemon_sprites VALUES ('0459','ユキカブリ');
INSERT INTO pokemon_sprites VALUES ('0460','ユキノオー');
INSERT INTO pokemon_sprites VALUES ('0460_mega','メガユキノオー');
INSERT INTO pokemon_sprites VALUES ('0461','マニューラ');
INSERT INTO pokemon_sprites VALUES ('0462','ジバコイル');
INSERT INTO pokemon_sprites VALUES ('0463','ベロベルト');
INSERT INTO pokemon_sprites VALUES ('0464','ドサイドン');
INSERT INTO pokemon_sprites VALUES ('0465','モジャンボ');
INSERT INTO pokemon_sprites VALUES ('0466','エレキブル');
INSERT INTO pokemon_sprites VALUES ('0467','ブーバーン');
INSERT INTO pokemon_sprites VALUES ('0468','トゲキッス');
INSERT INTO pokemon_sprites VALUES ('0469','メガヤンマ');
INSERT INTO pokemon_sprites VALUES ('0470','リーフィア');
INSERT INTO pokemon_sprites VALUES ('0471','グレイシア');
INSERT INTO pokemon_sprites VALUES ('0472','グライオン');
INSERT INTO pokemon_sprites VALUES ('0473','マンムー');
INSERT INTO pokemon_sprites VALUES ('0474','ポリゴンＺ');
INSERT INTO pokemon_sprites VALUES ('0475','エルレイド');
INSERT INTO pokemon_sprites VALUES ('0475_mega','メガエルレイド');
INSERT INTO pokemon_sprites VALUES ('0476','ダイノーズ');
INSERT INTO pokemon_sprites VALUES ('0477','ヨノワール');
INSERT INTO pokemon_sprites VALUES ('0478','ユキメノコ');
INSERT INTO pokemon_sprites VALUES ('0478_mega','メガユキメノコ');
INSERT INTO pokemon_sprites VALUES ('0479','ロトム');
INSERT INTO pokemon_sprites VALUES ('0479_fan','ロトム スピンロトム');
INSERT INTO pokemon_sprites VALUES ('0479_frost','ロトム フロストロトム');
INSERT INTO pokemon_sprites VALUES ('0479_heat','ロトム ヒートロトム');
INSERT INTO pokemon_sprites VALUES ('0479_mow','ロトム カットロトム');
INSERT INTO pokemon_sprites VALUES ('0479_wash','ロトム ウォッシュロトム');
INSERT INTO pokemon_sprites VALUES ('0480','ユクシー');
INSERT INTO pokemon_sprites VALUES ('0481','エムリット');
INSERT INTO pokemon_sprites VALUES ('0482','アグノム');
INSERT INTO pokemon_sprites VALUES ('0483','ディアルガ');
INSERT INTO pokemon_sprites VALUES ('0484','パルキア');
INSERT INTO pokemon_sprites VALUES ('0485','ヒードラン');
INSERT INTO pokemon_sprites VALUES ('0485_mega','メガヒードラン');
INSERT INTO pokemon_sprites VALUES ('0486','レジギガス');
INSERT INTO pokemon_sprites VALUES ('0487','ギラティナ');
INSERT INTO pokemon_sprites VALUES ('0487_another','ギラティナ アナザーフォルム');
INSERT INTO pokemon_sprites VALUES ('0487_origin','ギラティナ オリジンフォルム');
INSERT INTO pokemon_sprites VALUES ('0488','クレセリア');
INSERT INTO pokemon_sprites VALUES ('0489','フィオネ');
INSERT INTO pokemon_sprites VALUES ('0490','マナフィ');
INSERT INTO pokemon_sprites VALUES ('0491','ダークライ');
INSERT INTO pokemon_sprites VALUES ('0491_mega','メガダークライ');
INSERT INTO pokemon_sprites VALUES ('0492','シェイミ');
INSERT INTO pokemon_sprites VALUES ('0492_land','シェイミ ランドフォルム');
INSERT INTO pokemon_sprites VALUES ('0492_sky','シェイミ スカイフォルム');
INSERT INTO pokemon_sprites VALUES ('0493','アルセウス');

INSERT INTO pokemon_sprites VALUES ('0494','ビクティニ');
INSERT INTO pokemon_sprites VALUES ('0495','ツタージャ');
INSERT INTO pokemon_sprites VALUES ('0496','ジャノビー');
INSERT INTO pokemon_sprites VALUES ('0497','ジャローダ');
INSERT INTO pokemon_sprites VALUES ('0498','ポカブ');
INSERT INTO pokemon_sprites VALUES ('0499','チャオブー');
INSERT INTO pokemon_sprites VALUES ('0500','エンブオー');
INSERT INTO pokemon_sprites VALUES ('0500_mega','メガエンブオー');
INSERT INTO pokemon_sprites VALUES ('0501','ミジュマル');
INSERT INTO pokemon_sprites VALUES ('0502','フタチマル');
INSERT INTO pokemon_sprites VALUES ('0503','ダイケンキ');
INSERT INTO pokemon_sprites VALUES ('0503_hisui','ダイケンキ ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0504','ミネズミ');
INSERT INTO pokemon_sprites VALUES ('0505','ミルホッグ');
INSERT INTO pokemon_sprites VALUES ('0506','ヨーテリー');
INSERT INTO pokemon_sprites VALUES ('0507','ハーデリア');
INSERT INTO pokemon_sprites VALUES ('0508','ムーランド');
INSERT INTO pokemon_sprites VALUES ('0509','チョロネコ');
INSERT INTO pokemon_sprites VALUES ('0510','レパルダス');
INSERT INTO pokemon_sprites VALUES ('0511','ヤナップ');
INSERT INTO pokemon_sprites VALUES ('0512','ヤナッキー');
INSERT INTO pokemon_sprites VALUES ('0513','バオップ');
INSERT INTO pokemon_sprites VALUES ('0514','バオッキー');
INSERT INTO pokemon_sprites VALUES ('0515','ヒヤップ');
INSERT INTO pokemon_sprites VALUES ('0516','ヒヤッキー');
INSERT INTO pokemon_sprites VALUES ('0517','ムンナ');
INSERT INTO pokemon_sprites VALUES ('0518','ムシャーナ');
INSERT INTO pokemon_sprites VALUES ('0519','マメパト');
INSERT INTO pokemon_sprites VALUES ('0520','ハトーボー');
INSERT INTO pokemon_sprites VALUES ('0521','ケンホロウ');
INSERT INTO pokemon_sprites VALUES ('0521_m','ケンホロウ オスのすがた');
INSERT INTO pokemon_sprites VALUES ('0521_f','ケンホロウ メスのすがた');
INSERT INTO pokemon_sprites VALUES ('0522','シママ');
INSERT INTO pokemon_sprites VALUES ('0523','ゼブライカ');
INSERT INTO pokemon_sprites VALUES ('0524','ダンゴロ');
INSERT INTO pokemon_sprites VALUES ('0525','ガントル');
INSERT INTO pokemon_sprites VALUES ('0526','ギガイアス');
INSERT INTO pokemon_sprites VALUES ('0527','コロモリ');
INSERT INTO pokemon_sprites VALUES ('0528','ココロモリ');
INSERT INTO pokemon_sprites VALUES ('0529','モグリュー');
INSERT INTO pokemon_sprites VALUES ('0530','ドリュウズ');
INSERT INTO pokemon_sprites VALUES ('0530_mega','メガドリュウズ');
INSERT INTO pokemon_sprites VALUES ('0531','タブンネ');
INSERT INTO pokemon_sprites VALUES ('0531_mega','メガタブンネ');
INSERT INTO pokemon_sprites VALUES ('0532','ドッコラー');
INSERT INTO pokemon_sprites VALUES ('0533','ドテッコツ');
INSERT INTO pokemon_sprites VALUES ('0534','ローブシン');
INSERT INTO pokemon_sprites VALUES ('0535','オタマロ');
INSERT INTO pokemon_sprites VALUES ('0536','ガマガル');
INSERT INTO pokemon_sprites VALUES ('0537','ガマゲロゲ');
INSERT INTO pokemon_sprites VALUES ('0538','ナゲキ');
INSERT INTO pokemon_sprites VALUES ('0539','ダゲキ');
INSERT INTO pokemon_sprites VALUES ('0540','クルミル');
INSERT INTO pokemon_sprites VALUES ('0541','クルマユ');
INSERT INTO pokemon_sprites VALUES ('0542','ハハコモリ');
INSERT INTO pokemon_sprites VALUES ('0543','フシデ');
INSERT INTO pokemon_sprites VALUES ('0544','ホイーガ');
INSERT INTO pokemon_sprites VALUES ('0545','ペンドラー');
INSERT INTO pokemon_sprites VALUES ('0545_mega','メガペンドラー');
INSERT INTO pokemon_sprites VALUES ('0546','モンメン');
INSERT INTO pokemon_sprites VALUES ('0547','エルフーン');
INSERT INTO pokemon_sprites VALUES ('0548','チュリネ');
INSERT INTO pokemon_sprites VALUES ('0549','ドレディア');
INSERT INTO pokemon_sprites VALUES ('0549_hisui','ドレディア ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0550','バスラオ');
INSERT INTO pokemon_sprites VALUES ('0550_red-striped','バスラオ あかすじのすがた');
INSERT INTO pokemon_sprites VALUES ('0550_blue-striped','バスラオ あおすじのすがた');
INSERT INTO pokemon_sprites VALUES ('0550_white-striped','バスラオ しろすじのすがた');
INSERT INTO pokemon_sprites VALUES ('0551','メグロコ');
INSERT INTO pokemon_sprites VALUES ('0552','ワルビル');
INSERT INTO pokemon_sprites VALUES ('0553','ワルビアル');
INSERT INTO pokemon_sprites VALUES ('0554','ダルマッカ');
INSERT INTO pokemon_sprites VALUES ('0554_galar','ダルマッカ ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0555','ヒヒダルマ');
INSERT INTO pokemon_sprites VALUES ('0555_zen','ヒヒダルマ ダルマモード');
INSERT INTO pokemon_sprites VALUES ('0555_galar','ヒヒダルマ ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0555_galar_zen','ヒヒダルマ ガラルのすがた・ダルマモード');
INSERT INTO pokemon_sprites VALUES ('0556','マラカッチ');
INSERT INTO pokemon_sprites VALUES ('0557','イシズマイ');
INSERT INTO pokemon_sprites VALUES ('0558','イワパレス');
INSERT INTO pokemon_sprites VALUES ('0559','ズルッグ');
INSERT INTO pokemon_sprites VALUES ('0560','ズルズキン');
INSERT INTO pokemon_sprites VALUES ('0560_mega','メガズルズキン');
INSERT INTO pokemon_sprites VALUES ('0561','シンボラー');
INSERT INTO pokemon_sprites VALUES ('0562','デスマス');
INSERT INTO pokemon_sprites VALUES ('0562_galar','デスマス ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0563','デスカーン');
INSERT INTO pokemon_sprites VALUES ('0564','プロトーガ');
INSERT INTO pokemon_sprites VALUES ('0565','アバゴーラ');
INSERT INTO pokemon_sprites VALUES ('0566','アーケン');
INSERT INTO pokemon_sprites VALUES ('0567','アーケオス');
INSERT INTO pokemon_sprites VALUES ('0568','ヤブクロン');
INSERT INTO pokemon_sprites VALUES ('0569','ダストダス');
INSERT INTO pokemon_sprites VALUES ('0569_gmax','ダストダス キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0570','ゾロア');
INSERT INTO pokemon_sprites VALUES ('0571','ゾロアーク');
INSERT INTO pokemon_sprites VALUES ('0572','チラーミィ');
INSERT INTO pokemon_sprites VALUES ('0573','チラチーノ');
INSERT INTO pokemon_sprites VALUES ('0574','ゴチム');
INSERT INTO pokemon_sprites VALUES ('0575','ゴチミル');
INSERT INTO pokemon_sprites VALUES ('0576','ゴチルゼル');
INSERT INTO pokemon_sprites VALUES ('0577','ユニラン');
INSERT INTO pokemon_sprites VALUES ('0578','ダブラン');
INSERT INTO pokemon_sprites VALUES ('0579','ランクルス');
INSERT INTO pokemon_sprites VALUES ('0580','コアルヒー');
INSERT INTO pokemon_sprites VALUES ('0581','スワンナ');
INSERT INTO pokemon_sprites VALUES ('0582','バニプッチ');
INSERT INTO pokemon_sprites VALUES ('0583','バニリッチ');
INSERT INTO pokemon_sprites VALUES ('0584','バイバニラ');
INSERT INTO pokemon_sprites VALUES ('0585','シキジカ');
INSERT INTO pokemon_sprites VALUES ('0585_spring','シキジカ はる');
INSERT INTO pokemon_sprites VALUES ('0585_summer','シキジカ なつ');
INSERT INTO pokemon_sprites VALUES ('0585_autumn','シキジカ あき');
INSERT INTO pokemon_sprites VALUES ('0585_winter','シキジカ ふゆ');
INSERT INTO pokemon_sprites VALUES ('0586','メブキジカ');
INSERT INTO pokemon_sprites VALUES ('0586_spring','メブキジカ はる');
INSERT INTO pokemon_sprites VALUES ('0586_summer','メブキジカ なつ');
INSERT INTO pokemon_sprites VALUES ('0586_autumn','メブキジカ あき');
INSERT INTO pokemon_sprites VALUES ('0586_winter','メブキジカ ふゆ');
INSERT INTO pokemon_sprites VALUES ('0587','エモンガ');
INSERT INTO pokemon_sprites VALUES ('0588','カブルモ');
INSERT INTO pokemon_sprites VALUES ('0589','シュバルゴ');
INSERT INTO pokemon_sprites VALUES ('0590','タマゲタケ');
INSERT INTO pokemon_sprites VALUES ('0591','モロバレル');
INSERT INTO pokemon_sprites VALUES ('0592','プルリル');
INSERT INTO pokemon_sprites VALUES ('0592_m','プルリル オスのすがた');
INSERT INTO pokemon_sprites VALUES ('0592_f','プルリル メスのすがた');
INSERT INTO pokemon_sprites VALUES ('0593','ブルンゲル');
INSERT INTO pokemon_sprites VALUES ('0593_m','ブルンゲル オスのすがた');
INSERT INTO pokemon_sprites VALUES ('0593_f','ブルンゲル メスのすがた');
INSERT INTO pokemon_sprites VALUES ('0594','ママンボウ');
INSERT INTO pokemon_sprites VALUES ('0595','バチュル');
INSERT INTO pokemon_sprites VALUES ('0596','デンチュラ');
INSERT INTO pokemon_sprites VALUES ('0597','テッシード');
INSERT INTO pokemon_sprites VALUES ('0598','ナットレイ');
INSERT INTO pokemon_sprites VALUES ('0599','ギアル');
INSERT INTO pokemon_sprites VALUES ('0600','ギギアル');
INSERT INTO pokemon_sprites VALUES ('0601','ギギギアル');
INSERT INTO pokemon_sprites VALUES ('0602','シビシラス');
INSERT INTO pokemon_sprites VALUES ('0603','シビビール');
INSERT INTO pokemon_sprites VALUES ('0604','シビルドン');
INSERT INTO pokemon_sprites VALUES ('0604_mega','メガシビルドン');
INSERT INTO pokemon_sprites VALUES ('0605','リグレー');
INSERT INTO pokemon_sprites VALUES ('0606','オーベム');
INSERT INTO pokemon_sprites VALUES ('0607','ヒトモシ');
INSERT INTO pokemon_sprites VALUES ('0608','ランプラー');
INSERT INTO pokemon_sprites VALUES ('0609','シャンデラ');
INSERT INTO pokemon_sprites VALUES ('0609_mega','メガシャンデラ');
INSERT INTO pokemon_sprites VALUES ('0610','キバゴ');
INSERT INTO pokemon_sprites VALUES ('0611','オノンド');
INSERT INTO pokemon_sprites VALUES ('0612','オノノクス');
INSERT INTO pokemon_sprites VALUES ('0613','クマシュン');
INSERT INTO pokemon_sprites VALUES ('0614','ツンベアー');
INSERT INTO pokemon_sprites VALUES ('0615','フリージオ');
INSERT INTO pokemon_sprites VALUES ('0616','チョボマキ');
INSERT INTO pokemon_sprites VALUES ('0617','アギルダー');
INSERT INTO pokemon_sprites VALUES ('0618','マッギョ');
INSERT INTO pokemon_sprites VALUES ('0618_galar','マッギョ ガラルのすがた');
INSERT INTO pokemon_sprites VALUES ('0619','コジョフー');
INSERT INTO pokemon_sprites VALUES ('0620','コジョンド');
INSERT INTO pokemon_sprites VALUES ('0621','クリムガン');
INSERT INTO pokemon_sprites VALUES ('0622','ゴビット');
INSERT INTO pokemon_sprites VALUES ('0623','ゴルーグ');
INSERT INTO pokemon_sprites VALUES ('0623_mega','メガゴルーグ');
INSERT INTO pokemon_sprites VALUES ('0624','コマタナ');
INSERT INTO pokemon_sprites VALUES ('0625','キリキザン');
INSERT INTO pokemon_sprites VALUES ('0626','バッフロン');
INSERT INTO pokemon_sprites VALUES ('0627','ワシボン');
INSERT INTO pokemon_sprites VALUES ('0628','ウォーグル');
INSERT INTO pokemon_sprites VALUES ('0628_hisui','ウォーグル ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0629','バルチャイ');
INSERT INTO pokemon_sprites VALUES ('0630','バルジーナ');
INSERT INTO pokemon_sprites VALUES ('0631','クイタラン');
INSERT INTO pokemon_sprites VALUES ('0632','アイアント');
INSERT INTO pokemon_sprites VALUES ('0633','モノズ');
INSERT INTO pokemon_sprites VALUES ('0634','ジヘッド');
INSERT INTO pokemon_sprites VALUES ('0635','サザンドラ');
INSERT INTO pokemon_sprites VALUES ('0636','メラルバ');
INSERT INTO pokemon_sprites VALUES ('0637','ウルガモス');
INSERT INTO pokemon_sprites VALUES ('0638','コバルオン');
INSERT INTO pokemon_sprites VALUES ('0639','テラキオン');
INSERT INTO pokemon_sprites VALUES ('0640','ビリジオン');
INSERT INTO pokemon_sprites VALUES ('0641','トルネロス');
INSERT INTO pokemon_sprites VALUES ('0641_incarnate','トルネロス けしんフォルム');
INSERT INTO pokemon_sprites VALUES ('0641_therian','トルネロス れいじゅう');
INSERT INTO pokemon_sprites VALUES ('0642','ボルトロス');
INSERT INTO pokemon_sprites VALUES ('0642_incarnate','ボルトロス けしんフォルム');
INSERT INTO pokemon_sprites VALUES ('0642_therian','ボルトロス れいじゅう');
INSERT INTO pokemon_sprites VALUES ('0643','レシラム');
INSERT INTO pokemon_sprites VALUES ('0643_overdrive','レシラム オーバードライブ');
INSERT INTO pokemon_sprites VALUES ('0644','ゼクロム');
INSERT INTO pokemon_sprites VALUES ('0644_overdrive','ゼクロム オーバードライブ');
INSERT INTO pokemon_sprites VALUES ('0645','ランドロス');
INSERT INTO pokemon_sprites VALUES ('0645_incarnate','ランドロス けしんフォルム');
INSERT INTO pokemon_sprites VALUES ('0645_therian','ランドロス れいじゅう');
INSERT INTO pokemon_sprites VALUES ('0646','キュレム');
INSERT INTO pokemon_sprites VALUES ('0646_white','ホワイトキュレム');
INSERT INTO pokemon_sprites VALUES ('0646_white_overdrive','ホワイトキュレム オーバードライブ');
INSERT INTO pokemon_sprites VALUES ('0646_black','ブラックキュレム');
INSERT INTO pokemon_sprites VALUES ('0646_black_overdrive','ブラックキュレム オーバードライブ');
INSERT INTO pokemon_sprites VALUES ('0647','ケルディオ');
INSERT INTO pokemon_sprites VALUES ('0647_ordinary','ケルディオ いつものすがた');
INSERT INTO pokemon_sprites VALUES ('0647_resolute','ケルディオ かくごのすがた');
INSERT INTO pokemon_sprites VALUES ('0648','メロエッタ');
INSERT INTO pokemon_sprites VALUES ('0648_aria','メロエッタ ボイスフォルム');
INSERT INTO pokemon_sprites VALUES ('0648_pirouette','メロエッタ ステップフォルム');
INSERT INTO pokemon_sprites VALUES ('0649','ゲノセクト');

INSERT INTO pokemon_sprites VALUES ('0650','ハリマロン');
INSERT INTO pokemon_sprites VALUES ('0651','ハリボーグ');
INSERT INTO pokemon_sprites VALUES ('0652','ブリガロン');
INSERT INTO pokemon_sprites VALUES ('0652_mega','メガブリガロン');
INSERT INTO pokemon_sprites VALUES ('0653','フォッコ');
INSERT INTO pokemon_sprites VALUES ('0654','テールナー');
INSERT INTO pokemon_sprites VALUES ('0655','フォクシー');
INSERT INTO pokemon_sprites VALUES ('0655_mega','メガマフォクシー');
INSERT INTO pokemon_sprites VALUES ('0656','ケロマツ');
INSERT INTO pokemon_sprites VALUES ('0657','ゲコガシラ');
INSERT INTO pokemon_sprites VALUES ('0658','ゲッコウガ');
INSERT INTO pokemon_sprites VALUES ('0658_mega','メガゲッコウガ');
INSERT INTO pokemon_sprites VALUES ('0659','ホルビー');
INSERT INTO pokemon_sprites VALUES ('0660','ホルード');
INSERT INTO pokemon_sprites VALUES ('0661','ヤヤコマ');
INSERT INTO pokemon_sprites VALUES ('0662','ヒノヤコマ');
INSERT INTO pokemon_sprites VALUES ('0663','ファイアロー');
INSERT INTO pokemon_sprites VALUES ('0664','コフキムシ');
INSERT INTO pokemon_sprites VALUES ('0665','コフーライ');
INSERT INTO pokemon_sprites VALUES ('0666','ビビヨン');
INSERT INTO pokemon_sprites VALUES ('0667','シシコ');
INSERT INTO pokemon_sprites VALUES ('0668','カエンジシ');
INSERT INTO pokemon_sprites VALUES ('0668_m','カエンジシ オスのすがた');
INSERT INTO pokemon_sprites VALUES ('0668_f','カエンジシ メスのすがた');
INSERT INTO pokemon_sprites VALUES ('0668_mega','カエンジシ');
INSERT INTO pokemon_sprites VALUES ('0669','フラベベ');
INSERT INTO pokemon_sprites VALUES ('0670','フラエッテ');
INSERT INTO pokemon_sprites VALUES ('0670_etarnal','フラエッテ えいえんのはな');
INSERT INTO pokemon_sprites VALUES ('0670_eternal_mega','メガフラエッテ');
INSERT INTO pokemon_sprites VALUES ('0671','フラージェス');
INSERT INTO pokemon_sprites VALUES ('0672','メェークル');
INSERT INTO pokemon_sprites VALUES ('0673','ゴーゴート');
INSERT INTO pokemon_sprites VALUES ('0674','ヤンチャム');
INSERT INTO pokemon_sprites VALUES ('0675','ゴロンダ');
INSERT INTO pokemon_sprites VALUES ('0676','トリミアン');
INSERT INTO pokemon_sprites VALUES ('0677','ニャスパー');
INSERT INTO pokemon_sprites VALUES ('0678','ニャオニクス');
INSERT INTO pokemon_sprites VALUES ('0678_m','ニャオニクス オスのすがた');
INSERT INTO pokemon_sprites VALUES ('0678_f','ニャオニクス メスのすがた');
INSERT INTO pokemon_sprites VALUES ('0678_mega','メガニャオニクス');
INSERT INTO pokemon_sprites VALUES ('0679','ヒトツキ');
INSERT INTO pokemon_sprites VALUES ('0680','ニダンギル');
INSERT INTO pokemon_sprites VALUES ('0681','ギルガルド');
INSERT INTO pokemon_sprites VALUES ('0681_shield','ギルガルド シールドフォルム');
INSERT INTO pokemon_sprites VALUES ('0681_blade','ギルガルド ブレードフォルム');
INSERT INTO pokemon_sprites VALUES ('0682','シュシュプ');
INSERT INTO pokemon_sprites VALUES ('0683','フレフワン');
INSERT INTO pokemon_sprites VALUES ('0684','ペロッパフ');
INSERT INTO pokemon_sprites VALUES ('0685','ペロリーム');
INSERT INTO pokemon_sprites VALUES ('0686','マーイーカ');
INSERT INTO pokemon_sprites VALUES ('0687','カラマネロ');
INSERT INTO pokemon_sprites VALUES ('0687_mega','メガカラマネロ');
INSERT INTO pokemon_sprites VALUES ('0688','カメテテ');
INSERT INTO pokemon_sprites VALUES ('0689','ガメノデス');
INSERT INTO pokemon_sprites VALUES ('0689_mega','メガガメノデス');
INSERT INTO pokemon_sprites VALUES ('0690','クズモー');
INSERT INTO pokemon_sprites VALUES ('0691','ドラミドロ');
INSERT INTO pokemon_sprites VALUES ('0691_mega','メガドラミドロ');
INSERT INTO pokemon_sprites VALUES ('0692','ウデッポウ');
INSERT INTO pokemon_sprites VALUES ('0693','ブロスター');
INSERT INTO pokemon_sprites VALUES ('0694','エリキテル');
INSERT INTO pokemon_sprites VALUES ('0695','エレザード');
INSERT INTO pokemon_sprites VALUES ('0696','チゴラス');
INSERT INTO pokemon_sprites VALUES ('0697','ガチゴラス');
INSERT INTO pokemon_sprites VALUES ('0698','アマルス');
INSERT INTO pokemon_sprites VALUES ('0699','アマルルガ');
INSERT INTO pokemon_sprites VALUES ('0700','ニンフィア');
INSERT INTO pokemon_sprites VALUES ('0701','ルチャブル');
INSERT INTO pokemon_sprites VALUES ('0701_mega','メガルチャブル');
INSERT INTO pokemon_sprites VALUES ('0702','デデンネ');
INSERT INTO pokemon_sprites VALUES ('0703','メレシー');
INSERT INTO pokemon_sprites VALUES ('0704','ヌメラ');
INSERT INTO pokemon_sprites VALUES ('0705','ヌメイル');
INSERT INTO pokemon_sprites VALUES ('0705_hisui','ヌメイル ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0706','ヌメルゴン');
INSERT INTO pokemon_sprites VALUES ('0706_hisui','ヌメルゴン ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0707','クレッフィ');
INSERT INTO pokemon_sprites VALUES ('0708','ボクレー');
INSERT INTO pokemon_sprites VALUES ('0709','オーロット');
INSERT INTO pokemon_sprites VALUES ('0710','バケッチャ');
INSERT INTO pokemon_sprites VALUES ('0711','パンプジン');
INSERT INTO pokemon_sprites VALUES ('0712','カチコール');
INSERT INTO pokemon_sprites VALUES ('0713','クレベース');
INSERT INTO pokemon_sprites VALUES ('0713_hisui','クレベース ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0714','オンバット');
INSERT INTO pokemon_sprites VALUES ('0715','オンバーン');
INSERT INTO pokemon_sprites VALUES ('0716','ゼルネアス');
INSERT INTO pokemon_sprites VALUES ('0717','イベルタル');
INSERT INTO pokemon_sprites VALUES ('0718','ジガルデ');
INSERT INTO pokemon_sprites VALUES ('0718_10','ジガルデ 50%フォルム');
INSERT INTO pokemon_sprites VALUES ('0718_50','ジガルデ 10%フォルム');
INSERT INTO pokemon_sprites VALUES ('0718_complete','ジガルデ パーフェクトフォルム');
INSERT INTO pokemon_sprites VALUES ('0718_mega','メガジガルデ');
INSERT INTO pokemon_sprites VALUES ('0719','ディアンシー');
INSERT INTO pokemon_sprites VALUES ('0719_mega','メガディアンシー');
INSERT INTO pokemon_sprites VALUES ('0720','フーパ');
INSERT INTO pokemon_sprites VALUES ('0720_confined','フーパ いましめられしフーパ');
INSERT INTO pokemon_sprites VALUES ('0720_unbound','フーパ ときはなたれしフーパ');
INSERT INTO pokemon_sprites VALUES ('0721','ボルケニオン');

INSERT INTO pokemon_sprites VALUES ('0722','モクロー');
INSERT INTO pokemon_sprites VALUES ('0723','フクスロー');
INSERT INTO pokemon_sprites VALUES ('0724','ジュナイパー');
INSERT INTO pokemon_sprites VALUES ('0724_hisui','ジュナイパー ヒスイのすがた');
INSERT INTO pokemon_sprites VALUES ('0725','ニャビー');
INSERT INTO pokemon_sprites VALUES ('0726','ニャヒート');
INSERT INTO pokemon_sprites VALUES ('0727','ガオガエン');
INSERT INTO pokemon_sprites VALUES ('0728','アシマリ');
INSERT INTO pokemon_sprites VALUES ('0729','オシャマリ');
INSERT INTO pokemon_sprites VALUES ('0730','アシレーヌ');
INSERT INTO pokemon_sprites VALUES ('0731','ツツケラ');
INSERT INTO pokemon_sprites VALUES ('0732','ケララッパ');
INSERT INTO pokemon_sprites VALUES ('0733','ドデカバシ');
INSERT INTO pokemon_sprites VALUES ('0734','ヤングース');
INSERT INTO pokemon_sprites VALUES ('0735','デカグース');
INSERT INTO pokemon_sprites VALUES ('0736','アゴジムシ');
INSERT INTO pokemon_sprites VALUES ('0737','デンヂムシ');
INSERT INTO pokemon_sprites VALUES ('0738','クワガノン');
INSERT INTO pokemon_sprites VALUES ('0739','マケンカニ');
INSERT INTO pokemon_sprites VALUES ('0740','ケケンカニ');
INSERT INTO pokemon_sprites VALUES ('0740_mega','メガケケンカニ');
INSERT INTO pokemon_sprites VALUES ('0741','オドリドリ');
INSERT INTO pokemon_sprites VALUES ('0741_baile','オドリドリ めらめらスタイル');
INSERT INTO pokemon_sprites VALUES ('0741_pompom','オドリドリ ぱちぱちスタイル');
INSERT INTO pokemon_sprites VALUES ('0741_pau','オドリドリ ふらふらスタイル');
INSERT INTO pokemon_sprites VALUES ('0741_sensu','オドリドリ まいまいスタイル');
INSERT INTO pokemon_sprites VALUES ('0742','アブリー');
INSERT INTO pokemon_sprites VALUES ('0743','アブリボン');
INSERT INTO pokemon_sprites VALUES ('0744','イワンコ');
INSERT INTO pokemon_sprites VALUES ('0745','ルガルガン');
INSERT INTO pokemon_sprites VALUES ('0745_midday','ルガルガン まひるのすがた');
INSERT INTO pokemon_sprites VALUES ('0745_midnight','ルガルガン まよなかのすがた');
INSERT INTO pokemon_sprites VALUES ('0745_dusk','ルガルガン たそがれのすがた');
INSERT INTO pokemon_sprites VALUES ('0746','ヨワシ');
INSERT INTO pokemon_sprites VALUES ('0746_solo','ヨワシ たんどくのすがた');
INSERT INTO pokemon_sprites VALUES ('0746_school','ヨワシ むれたすがた');
INSERT INTO pokemon_sprites VALUES ('0747','ヒドイデ');
INSERT INTO pokemon_sprites VALUES ('0748','ドヒドイデ');
INSERT INTO pokemon_sprites VALUES ('0749','ドロバンコ');
INSERT INTO pokemon_sprites VALUES ('0750','バンバドロ');
INSERT INTO pokemon_sprites VALUES ('0751','シズクモ');
INSERT INTO pokemon_sprites VALUES ('0752','オニシズクモ');
INSERT INTO pokemon_sprites VALUES ('0753','カリキリ');
INSERT INTO pokemon_sprites VALUES ('0754','ラランテス');
INSERT INTO pokemon_sprites VALUES ('0755','ネマシュ');
INSERT INTO pokemon_sprites VALUES ('0756','マシェード');
INSERT INTO pokemon_sprites VALUES ('0757','ヤトウモリ');
INSERT INTO pokemon_sprites VALUES ('0758','エンニュート');
INSERT INTO pokemon_sprites VALUES ('0759','ヌイコグマ');
INSERT INTO pokemon_sprites VALUES ('0760','キテルグマ');
INSERT INTO pokemon_sprites VALUES ('0761','アマカジ');
INSERT INTO pokemon_sprites VALUES ('0762','アママイコ');
INSERT INTO pokemon_sprites VALUES ('0763','アマージョ');
INSERT INTO pokemon_sprites VALUES ('0764','キュワワー');
INSERT INTO pokemon_sprites VALUES ('0765','ヤレユータン');
INSERT INTO pokemon_sprites VALUES ('0766','ナゲツケサル');
INSERT INTO pokemon_sprites VALUES ('0767','コソクムシ');
INSERT INTO pokemon_sprites VALUES ('0768','グソクムシャ');
INSERT INTO pokemon_sprites VALUES ('0768_mega','メガグソクムシャ');
INSERT INTO pokemon_sprites VALUES ('0769','スナバァ');
INSERT INTO pokemon_sprites VALUES ('0770','シロデスナ');
INSERT INTO pokemon_sprites VALUES ('0771','ナマコブシ');
INSERT INTO pokemon_sprites VALUES ('0772','タイプ：ヌル');
INSERT INTO pokemon_sprites VALUES ('0773','シルヴァディ');
INSERT INTO pokemon_sprites VALUES ('0774','メテノ');
INSERT INTO pokemon_sprites VALUES ('0774_meteor','メテノ りゅうせいのすがた');
INSERT INTO pokemon_sprites VALUES ('0774_core_red','メテノ あかいろのコア');
INSERT INTO pokemon_sprites VALUES ('0775','ネッコアラ');
INSERT INTO pokemon_sprites VALUES ('0776','バクガメス');
INSERT INTO pokemon_sprites VALUES ('0777','トゲデマル');
INSERT INTO pokemon_sprites VALUES ('0778','ミミッキュ');
INSERT INTO pokemon_sprites VALUES ('0779','ハギギシリ');
INSERT INTO pokemon_sprites VALUES ('0780','ジジーロン');
INSERT INTO pokemon_sprites VALUES ('0780_mega','メガジジーロン');
INSERT INTO pokemon_sprites VALUES ('0781','ダダリン');
INSERT INTO pokemon_sprites VALUES ('0782','ジャラコ');
INSERT INTO pokemon_sprites VALUES ('0783','ジャランゴ');
INSERT INTO pokemon_sprites VALUES ('0784','ジャラランガ');
INSERT INTO pokemon_sprites VALUES ('0785','カプ・コケコ');
INSERT INTO pokemon_sprites VALUES ('0786','カプ・テテフ');
INSERT INTO pokemon_sprites VALUES ('0787','カプ・ブルル');
INSERT INTO pokemon_sprites VALUES ('0788','カプ・レヒレ');
INSERT INTO pokemon_sprites VALUES ('0789','コスモッグ');
INSERT INTO pokemon_sprites VALUES ('0790','コスモウム');
INSERT INTO pokemon_sprites VALUES ('0791','ソルガレオ');
INSERT INTO pokemon_sprites VALUES ('0791_radiant-sun','ソルガレオ ライジングフェーズ');
INSERT INTO pokemon_sprites VALUES ('0792','ルナアーラ');
INSERT INTO pokemon_sprites VALUES ('0792_full-moon','ルナアーラ フルムーンフェーズ');
INSERT INTO pokemon_sprites VALUES ('0793','ウツロイド');
INSERT INTO pokemon_sprites VALUES ('0794','マッシブーン');
INSERT INTO pokemon_sprites VALUES ('0795','フェローチェ');
INSERT INTO pokemon_sprites VALUES ('0796','デンジュモク');
INSERT INTO pokemon_sprites VALUES ('0797','テッカグヤ');
INSERT INTO pokemon_sprites VALUES ('0798','カミツルギ');
INSERT INTO pokemon_sprites VALUES ('0799','アクジキング');
INSERT INTO pokemon_sprites VALUES ('0800','ネクロズマ');
INSERT INTO pokemon_sprites VALUES ('0800_dusk-mane','ネクロズマ たそがれのたてがみ');
INSERT INTO pokemon_sprites VALUES ('0800_dawn-wings','ネクロズマ あかつきのつばさ');
INSERT INTO pokemon_sprites VALUES ('0800_ultra','ネクロズマ ウルトラネクロズマ');
INSERT INTO pokemon_sprites VALUES ('0801','マギアナ');
INSERT INTO pokemon_sprites VALUES ('0801_mega','メガマギアナ');
INSERT INTO pokemon_sprites VALUES ('0802','マーシャドー');
INSERT INTO pokemon_sprites VALUES ('0802_zenith','マーシャドー');
INSERT INTO pokemon_sprites VALUES ('0803','ベベノム');
INSERT INTO pokemon_sprites VALUES ('0804','アーゴヨン');
INSERT INTO pokemon_sprites VALUES ('0805','ツンデツンデ');
INSERT INTO pokemon_sprites VALUES ('0806','ズガドーン');
INSERT INTO pokemon_sprites VALUES ('0807','ゼラオラ');
INSERT INTO pokemon_sprites VALUES ('0807_mega','メガゼラオラ');
INSERT INTO pokemon_sprites VALUES ('0808','メルタン');
INSERT INTO pokemon_sprites VALUES ('0809','メルメタル');
INSERT INTO pokemon_sprites VALUES ('0809_gmax','メルメタル キョダイマックスのすがた');

INSERT INTO pokemon_sprites VALUES ('0810','サルノリ');
INSERT INTO pokemon_sprites VALUES ('0811','バチンキー');
INSERT INTO pokemon_sprites VALUES ('0812','ゴリランダー');
INSERT INTO pokemon_sprites VALUES ('0812_gmax','ゴリランダー キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0813','ヒバニー');
INSERT INTO pokemon_sprites VALUES ('0814','ラビフット');
INSERT INTO pokemon_sprites VALUES ('0815','エースバーン');
INSERT INTO pokemon_sprites VALUES ('0815_gmax','エースバーン キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0816','メッソン');
INSERT INTO pokemon_sprites VALUES ('0817','ジメレオン');
INSERT INTO pokemon_sprites VALUES ('0818','インテレオン');
INSERT INTO pokemon_sprites VALUES ('0818_gmax','インテレオン キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0819','ホシガリス');
INSERT INTO pokemon_sprites VALUES ('0820','ヨクバリス');
INSERT INTO pokemon_sprites VALUES ('0821','ココガラ');
INSERT INTO pokemon_sprites VALUES ('0822','アオガラス');
INSERT INTO pokemon_sprites VALUES ('0823','アーマーガア');
INSERT INTO pokemon_sprites VALUES ('0823_gmax','アーマーガア キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0824','サッチムシ');
INSERT INTO pokemon_sprites VALUES ('0825','レドームシ');
INSERT INTO pokemon_sprites VALUES ('0826','イオルブ');
INSERT INTO pokemon_sprites VALUES ('0826_gmax','イオルブ キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0827','クスネ');
INSERT INTO pokemon_sprites VALUES ('0828','フォクスライ');
INSERT INTO pokemon_sprites VALUES ('0829','ヒメンカ');
INSERT INTO pokemon_sprites VALUES ('0830','ワタシラガ');
INSERT INTO pokemon_sprites VALUES ('0831','ウールー');
INSERT INTO pokemon_sprites VALUES ('0832','バイウールー');
INSERT INTO pokemon_sprites VALUES ('0833','カムカメ');
INSERT INTO pokemon_sprites VALUES ('0834','カジリガメ');
INSERT INTO pokemon_sprites VALUES ('0834_gmax','カジリガメ キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0835','ワンパチ');
INSERT INTO pokemon_sprites VALUES ('0836','パルスワン');
INSERT INTO pokemon_sprites VALUES ('0837','タンドン');
INSERT INTO pokemon_sprites VALUES ('0838','トロッゴン');
INSERT INTO pokemon_sprites VALUES ('0839','セキタンザン');
INSERT INTO pokemon_sprites VALUES ('0839_gmax','セキタンザン キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0840','カジッチュ');
INSERT INTO pokemon_sprites VALUES ('0841','アップリュー');
INSERT INTO pokemon_sprites VALUES ('0841_gmax','アップリュー キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0842','タルップル');
INSERT INTO pokemon_sprites VALUES ('0842_gmax','タルップル キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0843','スナヘビ');
INSERT INTO pokemon_sprites VALUES ('0844','サダイジャ');
INSERT INTO pokemon_sprites VALUES ('0844_gmax','サダイジャ キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0845','ウッウ');
INSERT INTO pokemon_sprites VALUES ('0846','サシカマス');
INSERT INTO pokemon_sprites VALUES ('0847','カマスジョー');
INSERT INTO pokemon_sprites VALUES ('0848','エレズン');
INSERT INTO pokemon_sprites VALUES ('0849','ストリンダー');
INSERT INTO pokemon_sprites VALUES ('0849_amped','ストリンダー ハイなすがた');
INSERT INTO pokemon_sprites VALUES ('0849_low-key','ストリンダー ローなすがた');
INSERT INTO pokemon_sprites VALUES ('0849_gmax','ストリンダー キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0850','ヤクデ');
INSERT INTO pokemon_sprites VALUES ('0851','マルヤクデ');
INSERT INTO pokemon_sprites VALUES ('0851_gmax','マルヤクデ キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0852','タタッコ');
INSERT INTO pokemon_sprites VALUES ('0853','オトスパス');
INSERT INTO pokemon_sprites VALUES ('0854','ヤバチャ');
INSERT INTO pokemon_sprites VALUES ('0855','ポットデス');
INSERT INTO pokemon_sprites VALUES ('0856','ミブリム');
INSERT INTO pokemon_sprites VALUES ('0857','テブリム');
INSERT INTO pokemon_sprites VALUES ('0858','ブリムオン');
INSERT INTO pokemon_sprites VALUES ('0858_gmax','ブリムオン キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0859','ベロバー');
INSERT INTO pokemon_sprites VALUES ('0860','ギモー');
INSERT INTO pokemon_sprites VALUES ('0861','オーロンゲ');
INSERT INTO pokemon_sprites VALUES ('0861_gmax','オーロンゲ キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0862','タチフサグマ');
INSERT INTO pokemon_sprites VALUES ('0863','ニャイキング');
INSERT INTO pokemon_sprites VALUES ('0864','サニゴーン');
INSERT INTO pokemon_sprites VALUES ('0865','ネギガナイト');
INSERT INTO pokemon_sprites VALUES ('0866','バリコオル');
INSERT INTO pokemon_sprites VALUES ('0867','デスバーン');
INSERT INTO pokemon_sprites VALUES ('0868','マホミル');
INSERT INTO pokemon_sprites VALUES ('0869','マホイップ');
INSERT INTO pokemon_sprites VALUES ('0869_gmax','マホイップ キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0870','タイレーツ');
INSERT INTO pokemon_sprites VALUES ('0871','バチンウニ');
INSERT INTO pokemon_sprites VALUES ('0872','ユキハミ');
INSERT INTO pokemon_sprites VALUES ('0873','モスノウ');
INSERT INTO pokemon_sprites VALUES ('0874','イシヘンジン');
INSERT INTO pokemon_sprites VALUES ('0875','コオリッポ');
INSERT INTO pokemon_sprites VALUES ('0875_ice','コオリッポ アイスフェイス');
INSERT INTO pokemon_sprites VALUES ('0875_noice','コオリッポ ナイスフェイス');
INSERT INTO pokemon_sprites VALUES ('0876','イエッサン');
INSERT INTO pokemon_sprites VALUES ('0876_m','イエッサン オスのすがた');
INSERT INTO pokemon_sprites VALUES ('0876_f','イエッサン メスのすがた');
INSERT INTO pokemon_sprites VALUES ('0877','モルペコ');
INSERT INTO pokemon_sprites VALUES ('0877_full-belly','モルペコ まんぷくもよう');
INSERT INTO pokemon_sprites VALUES ('0877_hangry','モルペコ はらぺこもよう');
INSERT INTO pokemon_sprites VALUES ('0878','ゾウドウ');
INSERT INTO pokemon_sprites VALUES ('0879','ダイオウドウ');
INSERT INTO pokemon_sprites VALUES ('0879_gmax','ダイオウドウ キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0880','パッチラゴン');
INSERT INTO pokemon_sprites VALUES ('0881','パッチルドン');
INSERT INTO pokemon_sprites VALUES ('0882','ウオノラゴン');
INSERT INTO pokemon_sprites VALUES ('0883','ウオチルドン');
INSERT INTO pokemon_sprites VALUES ('0884','ジュラルドン');
INSERT INTO pokemon_sprites VALUES ('0884_gmax','ジュラルドン キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0885','ドラメシヤ');
INSERT INTO pokemon_sprites VALUES ('0886','ドロンチ');
INSERT INTO pokemon_sprites VALUES ('0887','ドラパルト');
INSERT INTO pokemon_sprites VALUES ('0888','ザシアン');
INSERT INTO pokemon_sprites VALUES ('0888_hero','ザシアン れきせんのゆうしゃ');
INSERT INTO pokemon_sprites VALUES ('0888_crowned','ザシアン けんのおう');
INSERT INTO pokemon_sprites VALUES ('0888_crowned_behemoth-blade','ザシアン けんのおう きょじゅうざん');
INSERT INTO pokemon_sprites VALUES ('0889','ザマゼンタ');
INSERT INTO pokemon_sprites VALUES ('0889_hero','ザマゼンタ れきせんのゆうしゃ');
INSERT INTO pokemon_sprites VALUES ('0889_crowned','ザマゼンタ たてのおう');
INSERT INTO pokemon_sprites VALUES ('0889_crowned_behemoth-bash','ザマゼンタ たてのおう きょじゅうだん');
INSERT INTO pokemon_sprites VALUES ('0890','ムゲンダイナ');
INSERT INTO pokemon_sprites VALUES ('0890_eternamax','ムゲンダイナ ムゲンダイマックス');
INSERT INTO pokemon_sprites VALUES ('0891','ダクマ');
INSERT INTO pokemon_sprites VALUES ('0892_single','ウーラオス いちげきのかた');
INSERT INTO pokemon_sprites VALUES ('0892_rapid','ウーラオス れんげきのかた');
INSERT INTO pokemon_sprites VALUES ('0892_single_gmax','ウーラオス いちげきのかた・キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0892_rapid_gmax','ウーラオス れんげきのかた・キョダイマックスのすがた');
INSERT INTO pokemon_sprites VALUES ('0893','ザルード');
INSERT INTO pokemon_sprites VALUES ('0894','レジエレキ');
INSERT INTO pokemon_sprites VALUES ('0895','レジドラゴ');
INSERT INTO pokemon_sprites VALUES ('0896','ブリザポス');
INSERT INTO pokemon_sprites VALUES ('0897','レイスポス');
INSERT INTO pokemon_sprites VALUES ('0898','バドレックス');
INSERT INTO pokemon_sprites VALUES ('0898_ice-rider','バドレックス はくばじょうのすがた');
INSERT INTO pokemon_sprites VALUES ('0898_shadow-rider','バドレックス こくばじょうのすがた');

INSERT INTO pokemon_sprites VALUES ('0899','アヤシシ');
INSERT INTO pokemon_sprites VALUES ('0900','バサギリ');
INSERT INTO pokemon_sprites VALUES ('0901','ガチグマ');
INSERT INTO pokemon_sprites VALUES ('0901_bloodmoon','ガチグマ アカツキ');
INSERT INTO pokemon_sprites VALUES ('0902','イダイトウ');
INSERT INTO pokemon_sprites VALUES ('0902_m','イダイトウ オスのすがた');
INSERT INTO pokemon_sprites VALUES ('0902_f','イダイトウ メスのすがた');
INSERT INTO pokemon_sprites VALUES ('0903','オオニューラ');
INSERT INTO pokemon_sprites VALUES ('0904','ハリーマン');
INSERT INTO pokemon_sprites VALUES ('0905','ラブトロス');
INSERT INTO pokemon_sprites VALUES ('0905_incarnate','ラブトロス けしんフォルム');
INSERT INTO pokemon_sprites VALUES ('0905_therian','ラブトロス れいじゅうフォルム');

INSERT INTO pokemon_sprites VALUES ('0906','ニャオハ');
INSERT INTO pokemon_sprites VALUES ('0907','ニャローテ');
INSERT INTO pokemon_sprites VALUES ('0908','マスカーニャ');
INSERT INTO pokemon_sprites VALUES ('0909','ホゲータ');
INSERT INTO pokemon_sprites VALUES ('0910','アチゲータ');
INSERT INTO pokemon_sprites VALUES ('0911','ラウドボーン');
INSERT INTO pokemon_sprites VALUES ('0912','クワッス');
INSERT INTO pokemon_sprites VALUES ('0913','ウェルカモ');
INSERT INTO pokemon_sprites VALUES ('0914','ウェーニバル');
INSERT INTO pokemon_sprites VALUES ('0915','グルトン');
INSERT INTO pokemon_sprites VALUES ('0916','パフュートン');
INSERT INTO pokemon_sprites VALUES ('0916_m','パフュートン オスのすがた');
INSERT INTO pokemon_sprites VALUES ('0916_f','パフュートン メスのすがた');
INSERT INTO pokemon_sprites VALUES ('0917','タマンチュラ');
INSERT INTO pokemon_sprites VALUES ('0918','ワナイダー');
INSERT INTO pokemon_sprites VALUES ('0919','マメバッタ');
INSERT INTO pokemon_sprites VALUES ('0920','エクスレッグ');
INSERT INTO pokemon_sprites VALUES ('0921','パモ');
INSERT INTO pokemon_sprites VALUES ('0922','パモット');
INSERT INTO pokemon_sprites VALUES ('0923','パーモット');
INSERT INTO pokemon_sprites VALUES ('0924','ワッカネズミ');
INSERT INTO pokemon_sprites VALUES ('0925','イッカネズミ');
INSERT INTO pokemon_sprites VALUES ('0925_family-of-three','イッカネズミ ３びきかぞく');
INSERT INTO pokemon_sprites VALUES ('0925_family-of-four','イッカネズミ ４ひきかぞく');
INSERT INTO pokemon_sprites VALUES ('0926','パピモッチ');
INSERT INTO pokemon_sprites VALUES ('0927','バウッツェル');
INSERT INTO pokemon_sprites VALUES ('0928','ミニーブ');
INSERT INTO pokemon_sprites VALUES ('0929','オリーニョ');
INSERT INTO pokemon_sprites VALUES ('0930','オリーヴァ');
INSERT INTO pokemon_sprites VALUES ('0931','イキリンコ');
INSERT INTO pokemon_sprites VALUES ('0931_blue','イキリンコ ブルーフェザー');
INSERT INTO pokemon_sprites VALUES ('0931_green','イキリンコ グリーンフェザー');
INSERT INTO pokemon_sprites VALUES ('0931_white','イキリンコ ホワイトフェザー');
INSERT INTO pokemon_sprites VALUES ('0931_yellow','イキリンコ イエローフェザー');
INSERT INTO pokemon_sprites VALUES ('0932','コジオ');
INSERT INTO pokemon_sprites VALUES ('0933','ジオヅム');
INSERT INTO pokemon_sprites VALUES ('0934','キョジオーン');
INSERT INTO pokemon_sprites VALUES ('0935','カルボウ');
INSERT INTO pokemon_sprites VALUES ('0936','グレンアルマ');
INSERT INTO pokemon_sprites VALUES ('0937','ソウブレイズ');
INSERT INTO pokemon_sprites VALUES ('0938','ズピカ');
INSERT INTO pokemon_sprites VALUES ('0939','ハラバリー');
INSERT INTO pokemon_sprites VALUES ('0940','カイデン');
INSERT INTO pokemon_sprites VALUES ('0941','タイカイデン');
INSERT INTO pokemon_sprites VALUES ('0942','オラチフ');
INSERT INTO pokemon_sprites VALUES ('0943','マフィティフ');
INSERT INTO pokemon_sprites VALUES ('0944','シルシュルー');
INSERT INTO pokemon_sprites VALUES ('0945','タギングル');
INSERT INTO pokemon_sprites VALUES ('0946','アノクサ');
INSERT INTO pokemon_sprites VALUES ('0947','アノホラグサ');
INSERT INTO pokemon_sprites VALUES ('0948','ノノクラゲ');
INSERT INTO pokemon_sprites VALUES ('0949','リククラゲ');
INSERT INTO pokemon_sprites VALUES ('0950','ガケガニ');
INSERT INTO pokemon_sprites VALUES ('0951','カプサイジ');
INSERT INTO pokemon_sprites VALUES ('0952','スコヴィラン');
INSERT INTO pokemon_sprites VALUES ('0952_mega','メガスコヴィラン');
INSERT INTO pokemon_sprites VALUES ('0953','シガロコ');
INSERT INTO pokemon_sprites VALUES ('0954','ベラカス');
INSERT INTO pokemon_sprites VALUES ('0955','ヒラヒナ');
INSERT INTO pokemon_sprites VALUES ('0956','クエスパトラ');
INSERT INTO pokemon_sprites VALUES ('0957','カヌチャン');
INSERT INTO pokemon_sprites VALUES ('0958','ナカヌチャン');
INSERT INTO pokemon_sprites VALUES ('0959','デカヌチャン');
INSERT INTO pokemon_sprites VALUES ('0960','ウミディグダ');
INSERT INTO pokemon_sprites VALUES ('0961','ウミトリオ');
INSERT INTO pokemon_sprites VALUES ('0962','オトシドリ');
INSERT INTO pokemon_sprites VALUES ('0963','ナミイルカ');
INSERT INTO pokemon_sprites VALUES ('0964','イルカマン');
INSERT INTO pokemon_sprites VALUES ('0964_zero','イルカマン ナイーブフォルム');
INSERT INTO pokemon_sprites VALUES ('0964_hero','イルカマン マイティフォルム');
INSERT INTO pokemon_sprites VALUES ('0965','ブロロン');
INSERT INTO pokemon_sprites VALUES ('0966','ブロロローム');
INSERT INTO pokemon_sprites VALUES ('0967','モトトカゲ');
INSERT INTO pokemon_sprites VALUES ('0968','ミミズズ');
INSERT INTO pokemon_sprites VALUES ('0969','キラーメ');
INSERT INTO pokemon_sprites VALUES ('0970','キラフロル');
INSERT INTO pokemon_sprites VALUES ('0970_mega','メガキラフロル');
INSERT INTO pokemon_sprites VALUES ('0971','ボチ');
INSERT INTO pokemon_sprites VALUES ('0972','ハカドッグ');
INSERT INTO pokemon_sprites VALUES ('0973','カラミンゴ');
INSERT INTO pokemon_sprites VALUES ('0974','アルクジラ');
INSERT INTO pokemon_sprites VALUES ('0975','ハルクジラ');
INSERT INTO pokemon_sprites VALUES ('0976','ミガルーサ');
INSERT INTO pokemon_sprites VALUES ('0977','ヘイラッシャ');
INSERT INTO pokemon_sprites VALUES ('0978','シャリタツ');
INSERT INTO pokemon_sprites VALUES ('0978_curly','シャリタツ そったすがた');
INSERT INTO pokemon_sprites VALUES ('0978_droopy','シャリタツ たれたすがた');
INSERT INTO pokemon_sprites VALUES ('0978_stretchy','シャリタツ のびたすがた');
INSERT INTO pokemon_sprites VALUES ('0978_curly_mega','メガシャリタツ そったすがた');
INSERT INTO pokemon_sprites VALUES ('0978_droopy_mega','メガシャリタツ たれたすがた');
INSERT INTO pokemon_sprites VALUES ('0978_stretchy_mega','メガシャリタツ のびたすがた');
INSERT INTO pokemon_sprites VALUES ('0979','コノヨザル');
INSERT INTO pokemon_sprites VALUES ('0980','ドオー');
INSERT INTO pokemon_sprites VALUES ('0981','リキキリン');
INSERT INTO pokemon_sprites VALUES ('0982','ノココッチ');
INSERT INTO pokemon_sprites VALUES ('0982_two-segment','ノココッチ ふたふしフォルム');
INSERT INTO pokemon_sprites VALUES ('0982_three-segment','ノココッチ みつふしフォルム');
INSERT INTO pokemon_sprites VALUES ('0983','ドドゲザン');
INSERT INTO pokemon_sprites VALUES ('0984','イダイナキバ');
INSERT INTO pokemon_sprites VALUES ('0985','サケブシッポ');
INSERT INTO pokemon_sprites VALUES ('0986','アラブルタケ');
INSERT INTO pokemon_sprites VALUES ('0987','ハバタクカミ');
INSERT INTO pokemon_sprites VALUES ('0988','チヲハウハネ');
INSERT INTO pokemon_sprites VALUES ('0989','スナノケガワ');
INSERT INTO pokemon_sprites VALUES ('0990','テツノワダチ');
INSERT INTO pokemon_sprites VALUES ('0991','テツノツツミ');
INSERT INTO pokemon_sprites VALUES ('0992','テツノカイナ');
INSERT INTO pokemon_sprites VALUES ('0993','テツノコウベ');
INSERT INTO pokemon_sprites VALUES ('0994','テツノドクガ');
INSERT INTO pokemon_sprites VALUES ('0995','テツノイバラ');
INSERT INTO pokemon_sprites VALUES ('0996','セビエ');
INSERT INTO pokemon_sprites VALUES ('0997','セゴール');
INSERT INTO pokemon_sprites VALUES ('0998','セグレイブ');
INSERT INTO pokemon_sprites VALUES ('0998_mega','メガセグレイブ');
INSERT INTO pokemon_sprites VALUES ('0999','コレクレー');
INSERT INTO pokemon_sprites VALUES ('0999_chest','コレクレー はこフォルム');
INSERT INTO pokemon_sprites VALUES ('0999_roaming','コレクレー とほフォルム');
INSERT INTO pokemon_sprites VALUES ('1000','サーフゴー');
INSERT INTO pokemon_sprites VALUES ('1001','チオンジェン');
INSERT INTO pokemon_sprites VALUES ('1002','パオジアン');
INSERT INTO pokemon_sprites VALUES ('1003','ディンルー');
INSERT INTO pokemon_sprites VALUES ('1004','イーユイ');
INSERT INTO pokemon_sprites VALUES ('1005','トドロクツキ');
INSERT INTO pokemon_sprites VALUES ('1006','テツノブジン');
INSERT INTO pokemon_sprites VALUES ('1007','コライドン');
INSERT INTO pokemon_sprites VALUES ('1008','ミライドン');
INSERT INTO pokemon_sprites VALUES ('1009','ウネルミナモ');
INSERT INTO pokemon_sprites VALUES ('1010','テツノイサハ');
INSERT INTO pokemon_sprites VALUES ('1011','カミッチュ');
INSERT INTO pokemon_sprites VALUES ('1012','チャデス');
INSERT INTO pokemon_sprites VALUES ('1013','ヤバソチャ');
INSERT INTO pokemon_sprites VALUES ('1014','イイネイヌ');
INSERT INTO pokemon_sprites VALUES ('1015','マシマシラ');
INSERT INTO pokemon_sprites VALUES ('1016','キチキギス');
INSERT INTO pokemon_sprites VALUES ('1017','オーガポン');
INSERT INTO pokemon_sprites VALUES ('1017_teal','オーガポン みどりのめん');
INSERT INTO pokemon_sprites VALUES ('1017_wellspring','オーガポン いどのめん');
INSERT INTO pokemon_sprites VALUES ('1017_hearthflame','オーガポン かまどのめん');
INSERT INTO pokemon_sprites VALUES ('1017_cornerstone','オーガポン いしずえのめん');
INSERT INTO pokemon_sprites VALUES ('1018','ブリジュラス');
INSERT INTO pokemon_sprites VALUES ('1019','カミツオロチ');
INSERT INTO pokemon_sprites VALUES ('1020','ウガツホムラ');
INSERT INTO pokemon_sprites VALUES ('1021','タケルライコ');
INSERT INTO pokemon_sprites VALUES ('1022','テツノイワオ');
INSERT INTO pokemon_sprites VALUES ('1023','テツノカシラ');
INSERT INTO pokemon_sprites VALUES ('1024','テラパゴス');
INSERT INTO pokemon_sprites VALUES ('1024_normal','テラパゴス ノーマルフォルム');
INSERT INTO pokemon_sprites VALUES ('1024_terastal','テラパゴス テラスタルフォルム');
INSERT INTO pokemon_sprites VALUES ('1024_stellar','テラパゴス ステラフォルム');
INSERT INTO pokemon_sprites VALUES ('1025','モモワロウ');
